### ISSUE TITLE
Doesn't seems to work with TypeScript 1.8 (1.8.0 beta, 1.8.5)

### ISSUE THREAD

**Issue by andruhon** [s-panferov/awesome-typescript-loader#108]
awesome-typescript-loader@0.17.0-rc.0 Erupts the following: 

```
ERROR in ./app/src/index.tsx
Module build failed: Error: Emit skipped
    at State.emit (C:\local_projects\howick\HLC2\node_modules\awesome-typescript-loader\dist\host.js:183:19)
    at transform (C:\local_projects\howick\HLC2\node_modules\awesome-typescript-loader\dist\index.js:100:40)
    at _callee3$ (C:\local_projects\howick\HLC2\node_modules\awesome-typescript-loader\dist\index.js:140:38)
    at tryCatch (C:\local_projects\howick\HLC2\node_modules\babel-regenerator-runtime\runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\local_projects\howick\HLC2\node_modules\babel-regenerator-runtime\runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\local_projects\howick\HLC2\node_modules\babel-regenerator-runtime\runtime.js:94:21)
    at fulfilled (C:\local_projects\howick\HLC2\node_modules\awesome-typescript-loader\dist\index.js:4:58)
    at run (C:\local_projects\howick\HLC2\node_modules\core-js\modules\es6.promise.js:104:47)
    at C:\local_projects\howick\HLC2\node_modules\core-js\modules\es6.promise.js:115:28
    at flush (C:\local_projects\howick\HLC2\node_modules\core-js\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)

```

**Comment by s-panferov** [comment]
@andruhon what kind of a project are you trying to build? JS? TS?

Could you please show me your `webpack.config.json` file?

**Comment by andruhon** [comment]
@s-panferov it is TypeScript

The webpack config file:
```JavaScript
module.exports = {
    entry: './app/src/index.tsx',
    output: {
        filename: 'app/dist/bundle.js'
    },
    externals: {
        libllc: "require('libllc')"
    },
    devtool: 'source-map',
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
    },
    target: "electron",
    module: {
        loaders: [
            { test: /\.tsx?$/, loader: 'awesome-typescript-loader' }
        ]
    }
}
```

tsconfig:
```JavaScript
{
  "compilerOptions": {
    "target": "es6",
    "jsx": "react",
    "noEmit": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "module": "commonjs"
  },
  "exclude": ["node_modules", "config", "dev_server.js"],
  "awesomeTypescriptLoaderOptions": {
    "library": "es6",
    "target": "es5"
  },
  "buildOnSave": false,
  "compileOnSave": false
}
```

**Comment by s-panferov** [comment]
@andruhon please try v0.17.0-rc.1

**Comment by andruhon** [comment]
It now works. Thank you!

So, it was caused by noEmit option?

**Comment by s-panferov** [comment]
Yes, `noEmit` option tells TS not to emit result files and this is not desirable behavior for loader, so we just ignore the option.

**Comment by andruhon** [comment]
I mistakenly thought that this option is required by the loader
