### ISSUE TITLE
having trouble with es6 generator syntax

### ISSUE THREAD

**Issue by episodeyang** [s-panferov/awesome-typescript-loader#112]
If I try to compile the following script:

```typescript
function* proc():void {
    yield 10;
    yield 20;
    return "done";
}
```

I get the following error message with @0.15.10 using node v4.3.2

```shell
ERROR in ./src/index.spec.ts
Module parse failed: ~/projects/luna-saga/node_modules/awesome-typescript-loader/dist.babel/index.js!~/projects/luna-saga/src/index.spec.ts Line 4: Unexpected number
You may need an appropriate loader to handle this file type.
| //import {Observable} from 'rxjs';
| function proc() {
|     yield 10;
|     yield 20;
|     return "done";
```

**Comment by episodeyang** [comment]
upgraded node to v5.9.1 but the error still persists.

**Comment by episodeyang** [comment]
Looks like setting `tsconfig.json` to target `ES6` fixed the issue. Now I just need to figure out how to publish ES6 module to npm without getting complains.

**Comment by s-panferov** [comment]
@episodeyang this is not the loader's issue. The problem is that webpack can't parse es6 syntax yet. You can try to use webpack `2.1.0-beta.4` version, but I'm not sure if it supports all es6 syntax already.

**Comment by episodeyang** [comment]
Thanks!

**Comment by Ciantic** [comment]
Hmm, I'm having Es6 problems too, with ts-loader it's simply like this: 

```
{ test: /\.tsx?$/, loaders: ['react-hot', 'babel?presets[]=es2015-loose', 'ts-loader?configFileName=tsconfig.webpack.json'], include: path.resolve(__dirname, "App") }
```

But with awesome-typescript-loader there is no way to add presets[]=es2015-loose ?

**Comment by Ciantic** [comment]
Duh, of course it works like this:

```
{ test: /\.tsx?$/, loaders: ['react-hot', 'babel?presets[]=es2015-loose', 'awesome-typescript-loader?tsconfig=tsconfig.webpack.json'], include: path.resolve(__dirname, "App") }
``` 

But it can't use the awesome-typescript-loaders "useBabel" because it can't take the presets

**Comment by drywolf** [comment]
Hi, I am trying to use ES6 generator syntax with function* & yield, but I get the following error:

	ERROR in ./src/index.tsx
	Module build failed: SyntaxError: c:/code/test-app/src/index.tsx: Unexpected token (37:18)
				pre = cur;
				cur += temp;
				yield cur;
			}
		},
		_a
		at Parser.pp.raise (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\location.js:24:13)
		at Parser.pp.unexpected (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\util.js:82:8)
		at Parser.pp.semicolon (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\util.js:69:81)
		at Parser.pp.parseExpressionStatement (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\statement.js:427:8)
		at Parser.parseExpressionStatement (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\plugins\flow.js:676:20)
		at Parser.pp.parseStatement (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\statement.js:142:21)
		at Parser.parseStatement (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\plugins\flow.js:655:22)
		at Parser.pp.parseBlock (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\statement.js:442:21)
		at Parser.pp.parseStatement (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\parser\statement.js:105:19)
		at Parser.parseStatement (c:\code\LxGit-upstream\ipp-project\apps\ipp-app\node_modules\babylon\lib\plugins\flow.js:655:22)

(The code sample that I use for testing is taken from the [babel examples page](https://babeljs.io/docs/learn-es2015/#generators))

In my tsconfig/awesome-ts-loader config I try to target es5 since I want to run the compiled code in the browser.

@s-panferov Is this error also caused by webpack, or is it a different one ?

Thanks
