### ISSUE TITLE
How to combine with json-loader?

### ISSUE THREAD

**Issue by unindented** [s-panferov/awesome-typescript-loader#114]
My Webpack config looks like this:

```js
module: {
  loaders: [
    {
      test: /\.json$/,
      exclude: /node_modules[\\\/]/,
      loader: 'json'
    },
    {
      test: /\.ts$/,
      exclude: /node_modules[\\\/]/,
      loader: 'awesome-typescript'
    }
  ]
}
```

When I try to load a JSON file like this:

```typescript
import payload from './fixtures/payload.json'
```

It will complain with something like:

```
Error: Could not find file: '.../yammer-normalizr/test/fixtures/feed_v1_next_page_expected.json'.
    at getValidSourceFile (.../yammer-normalizr/node_modules/typescript/lib/typescript.js:48843:23)
    at Object.getEmitOutput (.../yammer-normalizr/node_modules/typescript/lib/typescript.js:51905:30)
    at .../yammer-normalizr/node_modules/awesome-typescript-loader/dist/instance.js:274:56
    at Array.forEach (native)
    at Compiler.<anonymous> (.../yammer-normalizr/node_modules/awesome-typescript-loader/dist/instance.js:273:28)
    at Compiler.next (.../yammer-normalizr/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (.../yammer-normalizr/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (.../yammer-normalizr/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (.../yammer-normalizr/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (.../yammer-normalizr/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (.../yammer-normalizr/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (.../yammer-normalizr/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (.../yammer-normalizr/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (.../yammer-normalizr/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (.../yammer-normalizr/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (.../yammer-normalizr/node_modules/webpack/lib/Compilation.js:563:8)
```

The file is definitely there, so it looks to me like the TypeScript interpreter is trying to load the file, instead of Webpack processing it.

Any advice?

**Comment by Ciantic** [comment]
Did you try "tsc" the normal TypeScript compiler? Is it giving errors?

**Comment by unindented** [comment]
Aha, using the old `require` syntax does work.

**Comment by s-panferov** [comment]
@unindented sorry for the delay. This is not the loader's issue. When you use `import from` syntax, TS compiler wants to know the shape of the module. It doesn't know the shape, so it fails. This can be fixed by writing a declaration in one of `.d.ts` files. Or just by using pure `require` call.

**Comment by unindented** [comment]
@s-panferov but the error I got was "Could not find file: '.../yammer-normalizr/test/fixtures/feed_v1_next_page_expected.json'". That sounds like `tsc` is the one trying to load the JSON file, and not Webpack with its loaders?

**Comment by evenfrost** [comment]
FWIW: Declaration file does not help, fixed with `require`.
