### ISSUE TITLE
Deprecation warnings fixed by 0.18.0?

### ISSUE THREAD

**Issue by texastoland** [s-panferov/awesome-typescript-loader#139]
Just posting because I couldn't google it. Following commands yield a warning:

``` shell
$ npm i awesome-typescript-loader
~/test
└─┬ awesome-typescript-loader@0.17.0 
  …

$ node --trace-deprecation -e 'require("awesome-typescript-loader")'
(node:6422) DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
    at _interopRequireWildcard (~/test/node_modules/awesome-typescript-loader/dist.babel/cache.js:29:219)
    at Object.<anonymous> (~/test/node_modules/awesome-typescript-loader/dist.babel/cache.js:15:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/test/node_modules/awesome-typescript-loader/dist.babel/index.js:15:14)
(node:6422) DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
    at _interopRequireWildcard (~/test/node_modules/awesome-typescript-loader/dist.babel/cache.js:29:219)
    at Object.<anonymous> (~/test/node_modules/awesome-typescript-loader/dist.babel/cache.js:15:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/test/node_modules/awesome-typescript-loader/dist.babel/index.js:15:14)
```

`npm i awesome-typescript-loader@next` fixed it.

**Comment by AppShipIt** [comment]
Reopening in case you don't know 0.18 is still `next`.
