### ISSUE TITLE
Cannot resolve module 'electron'

### ISSUE THREAD

**Issue by mihe** [s-panferov/awesome-typescript-loader#157]
I'm trying to use atl in an Electron application, and I'm getting the following error:

```
Error: Cannot resolve module 'electron' in c:\Projects\hello-electron\src
    Required in c:\Projects\hello-electron\src\main.ts Error: Cannot resolve module 'electron' in c:\Projects\hello-electron\src
    Required in c:\Projects\hello-electron\src\main.ts
    at ResolutionError.Error (native)
    at new ResolutionError (c:\Projects\hello-electron\node_modules\awesome-typescript-loader\dist.babel\deps.js:592:88)
    at c:\Projects\hello-electron\node_modules\awesome-typescript-loader\dist.babel\deps.js:400:37
    at run (c:\Projects\hello-electron\node_modules\babel-polyfill\node_modules\core-js\modules\es6.promise.js:89:22)
    at c:\Projects\hello-electron\node_modules\babel-polyfill\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (c:\Projects\hello-electron\node_modules\babel-polyfill\node_modules\core-js\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

where `src/main.ts` contains:

``` typescript
/// <reference path="../typings/index.d.ts" />
import * as electron from 'electron';
```

where `[...]/typings/index.d.ts` contains:

``` typescript
/// <reference path="globals/github-electron/index.d.ts" />
/// <reference path="globals/node/index.d.ts" />
/// <reference path="modules/webpack/index.d.ts" />
```

where `[...]/github-electron/index.d.ts` contains:

``` typescript
// ...
declare module 'electron' {
    var electron: Electron.ElectronMainAndRenderer;
    export = electron;
}
// ...
```

and my webpack config contains `target: 'electron-main'`, which seems to do [a bunch of magic](https://github.com/webpack/webpack/blob/314c897682b556845fea36d329de8016d1740900/lib/WebpackOptionsApply.js#L117-L153) I don't really understand.

I assume this has something to do with the `electron` module being baked into the Electron runtime, kind of like how node has `fs` (which imports just fine) and whatnot.

I found that using `const electron = require('electron');` works, whilst using the import statement doesn't, which I guess means atl is only able to resolve modules that are imported with the `import` statement, which I'd like to use if possible.

Is there any way to tell atl that it shouldn't try resolving that module, or would that have some other unfortunate consequences?

**Comment by s-panferov** [comment]
@mihe, hello, thanks for your report. I think this is a bug, I'll try to fix it soon.

**Comment by s-panferov** [comment]
@mihe hello,

right now I'm working on the next version of the loader. Could you please try it (`2.0.0-rc.3` right now)? These errors must be solved there.

**Comment by nickytonline** [comment]
@mihe, the project I'm currently on uses electron and the target we use is `target: 'electron'`, not `target: 'electron-main'` and it works fine with webpack and awesome-typescript-loader.

**Comment by nickytonline** [comment]
@mihe, I just noticed in the code snippet you referenced that they appear to do the same thing. I wasn't aware they they had split it to have `'electron-main'` and `electron-renderer'`.

**Comment by mihe** [comment]
Thanks for looking into this @s-panferov . When trying `2.0.0-rc.3` (or any of the later release candidates) I seem to get a new error:
```
C:\Projects\hello-electron\node_modules\awesome-typescript-loader\src\host.ts:50
        return this.state.ts.ScriptSnapshot.fromString(file.text);
                                                           ^
TypeError: Cannot read property 'text' of undefined
    at Host.getScriptSnapshot (C:\Projects\hello-electron\node_modules\awesome-typescript-loader\src\host.ts:50:60)
    at HostCache.createEntry (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:52034:44)
    at HostCache.getOrCreateEntryByPath (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:52059:24)
    at getOrCreateSourceFileByPath (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:53111:53)
    at Object.getOrCreateSourceFile [as getSourceFile] (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:53104:24)
    at findSourceFile (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43908:29)
    at processSourceFile (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43856:27)
    at C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43949:17
    at Object.forEach (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:967:30)
    at processReferencedFiles (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43947:16)
    at findSourceFile (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43932:21)
    at processSourceFile (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43856:27)
    at processRootFile (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43760:13)
    at C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43228:60
    at Object.forEach (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:967:30)
    at Object.createProgram (C:\Projects\hello-electron\node_modules\typescript\lib\typescript.js:43228:16)
```
It might be worth mentioning that I'm using `typescript@next`, which at the moment equates to version `1.9.0-dev.20160620-1.0`.

@nickytonline Is the project you mentioned available somewhere? Would be helpful if I could compare our configurations.

**Comment by nickytonline** [comment]
@mihe, it's not an open source project, but I can probably just grab the configuration so you can take a peek at it. I'll try and get it to you tomorrow.

**Comment by nickytonline** [comment]
@mihe, here's what I could grab for my configuration as it's generated from functions in our build utilities package for the project and as I mentioned we're running TypeScript 1.8.10.

```
// imports and some other variables declared.
...
const config = {
  tslint: {
    failOnHint: false
  },
  devtool: '#source-map',
  debug: environment === 'dev',
  entry: [
    "source-map-support/register",
    "./src/main.ts"
  ],
  output: {
    path: "./dist/",
    libraryTarget: "commonjs2",
    filename: "bundle.js"
  },
  target: "electron",
  resolve: {
    dynamic: false,
    extensions: [
      "",
      ".ts",
      ".tsx",
      ".js",
      ".json"
    ]
  },
  externals: {},
  module: {
    preLoaders: [
      {
        test: /(\.ts)$/,
        loader: 'tslint-loader',
        exclude: /node_modules|lib/
      }
    ],
    loaders: [
      {
        test: /(\.ts)$/,
        loaders: ['awesome-typescript-loader'],
        exclude: /node_modules/
      },
      {
        test: /\.html$/,
        loader: 'html'
      },
      {
        test: /\.json$/,
        loaders: ['json']
      }
    ]
  },
  plugins: [
    {
      paths: [
        "dist"
      ],
      options: {
        root: "/some/root/path",
        verbose: true,
        dry: false
      }
    },
    {
      definitions: {
        "process.env.NODE_ENV": "\"dev\""
      }
    }
  ]
}
...
```

**Comment by mihe** [comment]
Thanks for the configuration snippet, @nickytonline . Unfortunately it didn't help.

As a test I threw together a very barebones Electron application (with stable TypeScript) which reproduces the error that I'm getting:

https://github.com/mihe/atl-resolve-issue

Feel free to test it, @s-panferov , to see if it helps you debug the issue, or perhaps reveal some obvious flaws that I'm making.

I also tried changing to ATL `2.0.0-rc.10` in that repo, but it throws the following error when I run `npm run build`:
```
C:\Projects\atl-resolve-issue\node_modules\awesome-typescript-loader\src\host.ts:53
            throw new Error(`Requested file is unknown: ${ fileName_ }`);
                  ^
Error: Requested file is unknown: C:\Projects\atl-resolve-issue\typings\index.d.ts
    at Host.getScriptSnapshot (C:\Projects\atl-resolve-issue\node_modules\awesome-typescript-loader\src\host.ts:53:19)
    at HostCache.createEntry (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:52503:44)
    at HostCache.getOrCreateEntryByPath (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:52528:24)
    at getOrCreateSourceFileByPath (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:53588:53)
    at Object.getOrCreateSourceFile [as getSourceFile] (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:53581:24)
    at findSourceFile (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44232:29)
    at processSourceFile (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44180:27)
    at C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44273:17
    at Object.forEach (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:972:30)
    at processReferencedFiles (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44271:16)
    at findSourceFile (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44256:21)
    at processSourceFile (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44180:27)
    at processRootFile (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:44084:13)
    at C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:43552:60
    at Object.forEach (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:972:30)
    at Object.createProgram (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:43552:16)
    at synchronizeHostData (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:53559:33)
    at Object.getProgram (C:\Projects\atl-resolve-issue\node_modules\typescript\lib\typescript.js:53659:13)
    at State.updateProgram (C:\Projects\atl-resolve-issue\node_modules\awesome-typescript-loader\src\host.ts:155:38)
    at Compiler.<anonymous> (C:\Projects\atl-resolve-issue\node_modules\awesome-typescript-loader\src\instance.ts:382:23)
    at Compiler.next (C:\Projects\atl-resolve-issue\node_modules\tapable\lib\Tapable.js:69:14)
    at Compiler.<anonymous> (C:\Projects\atl-resolve-issue\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (C:\Projects\atl-resolve-issue\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> (C:\Projects\atl-resolve-issue\node_modules\webpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> (C:\Projects\atl-resolve-issue\node_modules\webpack\lib\Compilation.js:577:13)
    at Compilation.applyPluginsAsync (C:\Projects\atl-resolve-issue\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\Projects\atl-resolve-issue\node_modules\webpack\lib\Compilation.js:572:10)
    at Compilation.applyPluginsAsync (C:\Projects\atl-resolve-issue\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (C:\Projects\atl-resolve-issue\node_modules\webpack\lib\Compilation.js:567:9)
    at Compilation.applyPluginsAsync (C:\Projects\atl-resolve-issue\node_modules\tapable\lib\Tapable.js:60:69)
```

**Comment by mihe** [comment]
Doesn't seem to happen anymore. Using the following versions:
- `electron@1.4.8`
- `webpack@1.13.3`
- `typescript@2.0.10`
- `awesome-typescript-loader@3.0.0-beta.9`
