### ISSUE TITLE
lib property not working with latest typescript@next

### ISSUE THREAD

**Issue by TheLarkInn** [s-panferov/awesome-typescript-loader#159]
I'm not sure if there is even a way to do this. But would it be possible to have a nightly build for a-t-loader that mimics the nightly `typescript@next` builds. It will help developers keep up with changes to typings, use @types and add support for `lib` option in `tsconfig.json`

**Comment by TheLarkInn** [comment]
I believe the other option is npm link typescript@next?

**Comment by s-panferov** [comment]
The loader doesn't have a bundled TypeScript, it assumes that you have `typescript` package in your node_modules. Just install `typescript@next` or use [`compiler`](https://github.com/s-panferov/awesome-typescript-loader#compiler-string-defaulttypescript) option.

**Comment by TheLarkInn** [comment]
Thanks for the response! I believe the root of my issue is the new `lib: ['es6', 'dom']` property not working for typescript@next. I'm going to close for now and double check my work.

**Comment by asvetliakov** [comment]
Just faced the same problem with new lib flag and latest typescript@next.
The problem that typescript throws diagnostic for these compiler parameters when used in transpileModule()
```
noEmitOnError
lib
```
Workaround is to use different tsconfig.json

**Comment by TheLarkInn** [comment]
Oh I wonder if it's because you are using `options.library` to create libs @s-panferov imma reopen for right now In case this needs to be tracked

**Comment by asvetliakov** [comment]
This looks related:
https://github.com/Microsoft/TypeScript/issues/9173

**Comment by s-panferov** [comment]
Ok, I'll take a look

**Comment by s-panferov** [comment]
@TheLarkInn  hello,

right now I'm working on the next version of the loader. Could you please try it (`2.0.0-rc.3` right now)? These errors must be solved there.

**Comment by TheLarkInn** [comment]
@s-panferov sorry was sleeping 😅 I can test this in an hour or so and I'll let you know.

**Comment by TheLarkInn** [comment]
@s-panferov the lib property is working great, however I would double-check/ensure that the loader also supports the TS2.0 `paths` mappings property, as it appeared it was not resolving properly and the `files` properties relative string paths also saw this issue.

**Comment by TheLarkInn** [comment]
I didn't want to put an issue in yet since it's still a WIP for you

**Comment by asvetliakov** [comment]
2.0.0-rc.10 gives me this error:
```
[Error: Requested file is unknown: C:\Users\asvet\work\applications\visitorapp\node_modules\typescript\lib\lib.dom.generated.d.ts]
```
tsconfig
```json
  "compilerOptions": {
    "target": "es5",
    "lib": ["es2015", "dom"],
    "module": "commonjs",
    "jsx": "react",
    "sourceMap": true,
    "experimentalDecorators": true,
    "noEmitOnError": true
  },
```
stack trace
```
Error: Debug Failure. False expression: Output generation failed Error: Debug Failure. False expression: Output generation failed           
    at Object.assert (C:\Users\asvet\work\applications\visitorapp\node_modules\typescript\lib\typescript.js:1762:23)                        
    at Object.transpileModule (C:\Users\asvet\work\applications\visitorapp\node_modules\typescript\lib\typescript.js:52215:18)              
    at State.fastEmit (C:\Users\asvet\work\applications\visitorapp\node_modules\awesome-typescript-loader\src\host.ts:226:39)               
    at transform (C:\Users\asvet\work\applications\visitorapp\node_modules\awesome-typescript-loader\src\index.ts:168:28)                   
    at transformationFunction (C:\Users\asvet\work\applications\visitorapp\node_modules\awesome-typescript-loader\src\index.ts:90:48)       
    at compiler (C:\Users\asvet\work\applications\visitorapp\node_modules\awesome-typescript-loader\src\index.ts:106:34)                    
    at Object.loader (C:\Users\asvet\work\applications\visitorapp\node_modules\awesome-typescript-loader\src\index.ts:19:18)                
    at WEBPACK_CORE_LOADER_EXECUTION (C:\Users\asvet\work\applications\visitorapp\node_modules\webpack-core\lib\NormalModuleMixin.js:155:71)
                                                                                                                                            
    at runSyncOrAsync (C:\Users\asvet\work\applications\visitorapp\node_modules\webpack-core\lib\NormalModuleMixin.js:155:93)               
    at nextLoader (C:\Users\asvet\work\applications\visitorapp\node_modules\webpack-core\lib\NormalModuleMixin.js:290:3)                    
    at C:\Users\asvet\work\applications\visitorapp\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5                                 
    at Storage.finished (C:\Users\asvet\work\applications\visitorapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)      
    at C:\Users\asvet\work\applications\visitorapp\node_modules\graceful-fs\graceful-fs.js:78:16                                            
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)                      
                                                     
[Error: Requested file is unknown: C:\Users\asvet\work\applications\visitorapp\node_modules\typescript\lib\lib.dom.generated.d.ts] 'Error: Requested file is unknown: C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\lib.dom.generated.d.ts\n    at Host.getScriptSnapshot (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\awesome-typescript-loader\\src\\host.ts:53:19)\n    at HostCache.createEntry (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:52034:44)\n    at HostCache.getOrCreateEntryByPath (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:52059:24)\n   at getOrCreateSourceFileByPath (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:53111:53)\n at Object.getOrCreateSourceFile [as getSourceFile] (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\type
script.js:53104:24)\n    at findSourceFile (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:4
3908:29)\n    at processSourceFile (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43856:27)
\n    at C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43949:17\n    at Object.forEach (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:967:30)\n    at processReferencedFiles (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43947:16)\n    at findSourceFile (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43932:21)\n    at processSourceFile (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43856:27)\n    at processRootFile (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43760:13)\n    at C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43228:60\n    at Object.forEach (C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:967:30)\n    at Object.createProgram(C:\\Users\\asvet\\work\\applications\\visitorapp\\node_modules\\typescript\\lib\\typescript.js:43228:16)'                                                                                                                      
```

**Comment by s-panferov** [comment]
@asvetliakov ok, I'll try to debug on windows.

**Comment by s-panferov** [comment]
Should be fixed in latest `2.0.0` release candidates.

**Comment by mover96** [comment]
@s-panferov, I am getting a similar error to @asvetliakov and I am on Windows as well. My build works fine with `ts-loader`, and all I did was switch to `awesome-typescript-loader`, and I added the following to my `tsconfig.json`:
```js
"awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  }
```
And I get the following error: `Error: Debug Failure. False expression: Output generation failed Error: Debug Failure. False expression: Output generation failed`

And here is the stacktrace:
```js
Error: Debug Failure. False expression: Output generation failed Error: Debug Failure. False expression: Output generation failed
   at Object.assert (C:\Code\stash\app\node_modules\typescript\lib\typescript.js:1721:23)
   at Object.transpileModule (C:\Code\stash\app\node_modules\typescript\lib\typescript.js:48178:18)
   at State.fastEmit (C:\Code\stash\app\node_modules\awesome-typescript-loader\src\host.ts:253:39)
   at transform (C:\Code\stash\app\node_modules\awesome-typescript-loader\src\index.ts:166:28)
   at transformationFunction (C:\Code\stash\app\node_modules\awesome-typescript-loader\src\index.ts:91:48)
   at compiler (C:\Code\stash\app\node_modules\awesome-typescript-loader\src\index.ts:107:34)
   at Object.loader (C:\Code\stash\app\node_modules\awesome-typescript-loader\src\index.ts:20:18)
   at LOADER_EXECUTION (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:95:14)
   at runSyncOrAsync (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:96:4)
   at iterateNormalLoaders (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:200:2)
   at iterateNormalLoaders (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:189:10)
   at C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:204:3
   at Object.context.callback (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:87:13)
   at Object.module.exports (C:\Code\stash\app\node_modules\angular2-template-loader\index.js:32:10)
   at LOADER_EXECUTION (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:95:14)
   at runSyncOrAsync (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:96:4)
   at iterateNormalLoaders (C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:200:2)
   at C:\Code\stash\app\node_modules\loader-runner\lib\LoaderRunner.js:173:4
   at Storage.finished (C:\Code\stash\app\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:39:16)
   at C:\Code\stash\app\node_modules\graceful-fs\graceful-fs.js:78:16
   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

My `awesome-typescript-loader` version is `2.1.1` and my `typescript` version is `1.8.10`. And here is my `tsconfig.json` for reference:
```js
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "mapRoot": "/",
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "../dist/",
    "rootDir": ".",
    "sourceMap": true,
    "target": "es5",
    "inlineSources": true
  },
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  }
}
```
Any ideas?

**Comment by asvetliakov** [comment]
@mover96 I think 2.0 versions are for TS 2.0+ only

**Comment by mover96** [comment]
@asvetliakov, I downgraded to atl `1.1.1` and I am receving the following error:
```js
Error: Debug Failure. False expression: Output generation failed Error: Debug Failure. False expression: Output generation failed
   at Object.assert (C:\Code\stash\app\node_modules\typescript\lib\typescript.js:1721:23)
   at Object.transpileModule (C:\Code\stash\app\node_modules\typescript\lib\typescript.js:48178:18)
   at State.fastEmit (C:\Code\stash\app\node_modules\awesome-typescript-loader\dist.babel\host.js:302:43)
   at transform (C:\Code\stash\app\node_modules\awesome-typescript-loader\dist.babel\index.js:215:53)
   at _callee3$ (C:\Code\stash\app\node_modules\awesome-typescript-loader\dist.babel\index.js:265:42)
   at tryCatch (C:\Code\stash\app\node_modules\regenerator-runtime\runtime.js:62:40)
   at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Code\stash\app\node_modules\regenerator-runtime\runtime.js:336:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Code\stash\app\node_modules\regenerator-runtime\runtime.js:95:21)
   at fulfilled (C:\Code\stash\app\node_modules\awesome-typescript-loader\dist.babel\index.js:31:32)
   at run (C:\Code\stash\app\node_modules\core-js\modules\es6.promise.js:89:22)
   at C:\Code\stash\app\node_modules\core-js\modules\es6.promise.js:102:28
   at flush (C:\Code\stash\app\node_modules\core-js\modules\_microtask.js:18:9)
   at _combinedTickCallback (internal/process/next_tick.js:67:7)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

However I am not sure if this is directly related to this issue anymore, should I create a new one?
