### ISSUE TITLE
ReferenceError occured when adding something to types in tsconfig.json

### ISSUE THREAD

**Issue by t246246** [s-panferov/awesome-typescript-loader#191]
My tsconfig.json
```
	"compilerOptions": {
		"target": "es2015",
		"module": "es2015",
		"lib": ["dom", "es2015"],
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"removeComments": false,
		"noImplicitAny": false,
		"suppressImplicitAnyIndexErrors": false,
		"declaration": false,
		"typeRoots": ["node_modules/@types"],
		"types" : ["node"]
	},
	"compileOnSave": false,
	"buildOnSave": false,
	"exclude": [
		"node_modules"
	]
}
```
(Note I installed type definitions with `npm install @types/node -D`.)

in webpack.config.js

```
	loader: 'awesome-typescript-loader?+useBabel&+useCache+forkChecker=true'
```

When running webpack with `npm start`, the error is:
```
[ReferenceError: ts is not defined] 'ReferenceError: ts is not defined\n    at /Users/t246246/work/plunk/node_modules/awesome-typescript-loader/src/host.ts:143:23\n    at Array.forEach (native)\n    at State.loadTypesFromConfig (/Users/t246246/work/plunk/node_modules/awesome-typescript-loader/src/host.ts:142:27)\n    at new State (/Users/t246246work/plunk/node_modules/awesome-typescript-loader/src/host.ts:136:14)\n    at Object.ensureInstance (/Users/t246246/work/plunk/node_modules/awesome-typescript-loader/src/instance.ts:151:19)\n    at compiler (/Users/t246246/work/plunk/node_modules/awesome-typescript-loader/src/index.ts:39:20)\n    at Object.loader (/Users/t246246/work/plunk/node_modules/awesome-typescript-loader/src/index.ts:20:18)\n    at LOADER_EXECUTION (/Users/t246246/work/plunk/node_modules/loader-runner/lib/LoaderRunner.js:95:14)\n    at runSyncOrAsync (/Users/t246246/work/plunk/node_modules/loader-runner/lib/LoaderRunner.js:96:4)\n    at iterateNormalLoaders (/Users/t246246/work/plunk/node_modules/loader-runner/lib/LoaderRunner.js:200:2)'
```

versions of modules:
```
awesome-typescript-loader: 2.0.1
typescript: 2.1.0-dev.20160714
webpack: 2.1.0-beta.17
```
Using ts-loader it works with no problem.
```
	loader: 'babel-loader!ts-loader'
```

**Comment by t246246** [comment]
Solved at awesome-typescript-loader: 2.0.2.
