### ISSUE TITLE
v2.2.0 file not found

### ISSUE THREAD

**Issue by beckend** [s-panferov/awesome-typescript-loader#210]
`tsconfig.json`:
```javascript
...
  "files": [
    "typings/index.d.ts"
  ],
...
```
`Module build failed: Error: ENOENT: no such file or directory, open '/Users/linken/Coding/REACT/myProject/Users/linken/Coding/REACT/myProject/Users/linken/Coding/REACT/myProject/typings/index.d.ts'`.

There are duplicates in the path in `v2.2.0`, works fine in `v2.1.1`.

**Comment by fgambino** [comment]
This is happening to me too on Windows.

**Comment by DcsMarcRemolt** [comment]
Can confirm the effect. Just upgrading from 2.1.1 broke the build with the same error (different file but filesystem path joined multiple times).

**Comment by s-panferov** [comment]
Confirmed, fixed in v2.2.1

**Comment by DxCx** [comment]
Hi @s-panferov 

I've encountered a bug that looks similar to me,
i have a typings.d.ts files that return ENOENT.
(The base path is tripled)
after debugging i nailed out this commit: 71d01b1caec0346b30a91045ee04fa09e63a6bb3

Note that <path> is censored, but the same each time it is showen (/home/....../project_dir)
ERROR in ./src/main.ts
Module build failed: Error: ENOENT: no such file or directory, open '<path>/<path>/src/<path>/src/typings.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at State.readFile (<path>/node_modules/awesome-typescript-loader/src/host.ts:319:19)
    at State.readFileAndAdd (<path>/node_modules/awesome-typescript-loader/src/host.ts:323:25)
    at FileAnalyzer.checkDependencies (<path>/node_modules/awesome-typescript-loader/src/deps.ts:42:28)
    at <path>/node_modules/awesome-typescript-loader/src/index.ts:205:59
    at Array.forEach (native)
    at invokeKnownFilesOneTime (<path>/node_modules/awesome-typescript-loader/src/index.ts:205:14)
    at compiler (<path>/node_modules/awesome-typescript-loader/src/index.ts:56:5)
    at Object.loader (<path>/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main

can you please confirm this is the same issue?

**Comment by DxCx** [comment]
@s-panferov  Nvm,
i've just seen 2.2.1 is published,
verified your fix (Both Commit makes sense and tested it) - it is working, Thanks!
