### ISSUE TITLE
Issue with 2.2.2 and 2.2.3

### ISSUE THREAD

**Issue by jmc265** [s-panferov/awesome-typescript-loader#226]
This issue is not present when using 2.2.1.

The build results in a failure with message:

```
ERROR in ./src/main.ts                                                                                                                                                                              
Module build failed: TypeError: Cannot read property 'directoryExists' of undefined                                                                                                                 
    at Object.getAutomaticTypeDirectiveNames (/Users/james/Documents/Workspace/.../node_modules/typescript/lib/typescript.js:43865:17)                                     
    at State.loadTypesFromConfig (/Users/james/Documents/Workspace/.../node_modules/awesome-typescript-loader/src/host.ts:150:36)                                          
    at new State (/Users/james/Documents/Workspace/.../node_modules/awesome-typescript-loader/src/host.ts:144:14)                                                          
    at Object.ensureInstance (/Users/james/Documents/Workspace/.../node_modules/awesome-typescript-loader/src/instance.ts:150:19)                                          
    at compiler (/Users/james/Documents/Workspace/.../node_modules/awesome-typescript-loader/src/index.ts:37:20)                                                           
    at Object.loader (/Users/james/Documents/Workspace/.../node_modules/awesome-typescript-loader/src/index.ts:18:18)
```

Can provide more information if needed.

**Comment by textbook** [comment]
This happens because `host.ts:150` passes two arguments to `getAutomaticTypeDirectiveNames`:

```
const directives = this.ts.getAutomaticTypeDirectiveNames(options, this.compilerHost);
```

which expects three (`typescript.d.ts:1880`):

```
function getAutomaticTypeDirectiveNames(options: CompilerOptions, rootFiles: string[], host: CompilerHost): string[];
```

(using `typescript@2.0.0`)

**Comment by s-panferov** [comment]
typescript@2.0.0 is obsolete, please use `typescript@rc` which introduces some fixes and behavior changes.

**Comment by textbook** [comment]
`typescript@beta` is still 2.0.0, and that's what Angular CLI requires (see e.g. https://github.com/angular/angular-cli/issues/1917). Guess this is what happens when you try to hit a moving target...

**Comment by s-panferov** [comment]
@textbook `rc` > `beta` according to http://semver.org/, so I believe `angular-cli` should move to the latest stable version, which is `rc` `2.0.2`
