### ISSUE TITLE
2.2.3 only compatible with typescript@2.0.2

### ISSUE THREAD

**Issue by mvestergaard** [s-panferov/awesome-typescript-loader#228]
When using typescript@2.0.0 you get this error
```
TypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (/Users/mv/dev/js/product-designer/node_modules/typescript/lib/typescript.js:43865:17)
    at State.loadTypesFromConfig (/Users/mv/dev/js/product-designer/node_modules/awesome-typescript-loader/src/host.ts:150:36)
    at new State (/Users/mv/dev/js/product-designer/node_modules/awesome-typescript-loader/src/host.ts:144:14)
    at Object.ensureInstance (/Users/mv/dev/js/product-designer/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/Users/mv/dev/js/product-designer/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/mv/dev/js/product-designer/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at iterateNormalLoaders (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:189:10)
    at /Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:204:3
    at context.callback (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:87:13)
    at Object.module.exports (/Users/mv/dev/js/product-designer/node_modules/tslint-loader/index.js:104:3)
    at LOADER_EXECUTION (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/Users/mv/dev/js/product-designer/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
```

**Comment by s-panferov** [comment]
`typescript@2.0.0` was a `beta` release and it's obsolete already, because there is an `rc` release already with bugfixes and some breaking changes in API. I have no time and energy to support obsolete releases, so please use `typescript@2.0.2` or switch to `ts-loader`.
