### ISSUE TITLE
v2.2.3, v2.2.2 error

### ISSUE THREAD

**Issue by beckend** [s-panferov/awesome-typescript-loader#229]
Only happens in versions newer than v2.2.1:
<details>
  <summary>Long trace</summary>
`
webpack building...
 10% building modules 3/7 modules 4 active ...pack-hot-middleware/process-update.jsTypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (/User/linken/Coding/myProject/node_modules/typescript/lib/typescript.js:43865:17)
    at State.loadTypesFromConfig (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/host.ts:150:36)
    at new State (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/host.ts:144:14)
    at Object.ensureInstance (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at /User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:173:4
    at Storage.finished (/User/linken/Coding/myProject/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /User/linken/Coding/myProject/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) 'TypeError: Cannot read property \'directoryExists\' of undefined\n    at Object.getAutomaticTypeDirectiveNames (/User/linken/Coding/myProject/node_modules/typescript/lib/typescript.js:43865:17)\n    at State.loadTypesFromConfig (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/host.ts:150:36)\n    at new State (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/host.ts:144:14)\n    at Object.ensureInstance (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/instance.ts:150:19)\n    at compiler (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/User/linken/Coding/myProject/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:95:14)\n    at runSyncOrAsync (/User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:96:4)\n    at iterateNormalLoaders (/User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:200:2)\n    at /User/linken/Coding/myProject/node_modules/loader-runner/lib/LoaderRunner.js:173:4\n    at Storage.finished (/User/linken/Coding/myProject/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /User/linken/Coding/myProject/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)'
`
</details>

**Comment by s-panferov** [comment]
Dup of #228
