### ISSUE TITLE
Providing a custom d.ts file for an imported library throws a file not found exception

### ISSUE THREAD

**Issue by Tragetaschen** [s-panferov/awesome-typescript-loader#230]
I have migrated from 2.1.1 to 2.2.3 for TypeScript 2.0.2 support and now webpack throws an exception not finding a custom `d.ts` file in my project.

```
{ Error: ENOENT: no such file or directory, open 'C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\Client\Client\jstz.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at State.readFile (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\host.ts:321:19)
    at State.readFileAndAdd (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\host.ts:325:25)
    at FileAnalyzer.checkDependencies (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\deps.ts:43:28)
    at C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\index.ts:205:59
    at Array.forEach (native)
    at invokeKnownFilesOneTime (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\index.ts:205:14)
    at compiler (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\index.ts:56:5)
    at Object.loader (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\awesome-typescript-loader\src\index.ts:18:18)
    at LOADER_EXECUTION (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\loader-runner\lib\LoaderRunner.js:95:14)
    at runSyncOrAsync (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\loader-runner\lib\LoaderRunner.js:96:4)
    at iterateNormalLoaders (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\loader-runner\lib\LoaderRunner.js:200:2)
    at C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\loader-runner\lib\LoaderRunner.js:173:4
    at Storage.finished (C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:39:16)
    at C:\Users\kairu\Source\Repos\awesome-typescript-loader-dts-issue\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\Client\\Client\\jstz.d.ts' } 'Error: ENOENT: no such file or directory, open \'C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\Client\\Client\\jstz.d.ts\'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at State.readFile (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\host.ts:321:19)\n    at State.readFileAndAdd (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\host.ts:325:25)\n    at FileAnalyzer.checkDependencies (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\deps.ts:43:28)\n    at C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\index.ts:205:59\n    at Array.forEach (native)\n    at invokeKnownFilesOneTime (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\index.ts:205:14)\n    at compiler (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\index.ts:56:5)\n    at Object.loader (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\awesome-typescript-loader\\src\\index.ts:18:18)\n    at LOADER_EXECUTION (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\loader-runner\\lib\\LoaderRunner.js:95:14)\n    at runSyncOrAsync (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\loader-runner\\lib\\LoaderRunner.js:96:4)\n    at iterateNormalLoaders (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\loader-runner\\lib\\LoaderRunner.js:200:2)\n    at C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\loader-runner\\lib\\LoaderRunner.js:173:4\n    at Storage.finished (C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\enhanced-resolve\\lib\\CachedInputFileSystem.js:39:16)\n    at C:\\Users\\kairu\\Source\\Repos\\awesome-typescript-loader-dts-issue\\node_modules\\graceful-fs\\graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)'
```

The `jstz.d.ts` file is in the `Client` folder, but awesome-typescript-loader tries to load it from the `Client\Client` folder instead.

A reproduction is here: https://github.com/Tragetaschen/awesome-typescript-loader-dts-issue

**Comment by Tragetaschen** [comment]
That was fast. Sweet!
