### ISSUE TITLE
Upgrading webpack from 2.1.0-beta.22 to 2.1.0-beta.23+ throws error

### ISSUE THREAD

**Issue by gregbown** [s-panferov/awesome-typescript-loader#241]
ERROR in ./apps/common/includes/angular2.libs.ts
    Module build failed: Error: parseQuery should get a string as first argument
        at Object.parseQuery (C:\...\node_modules\loader-utils\index.js:68:9)
        at compiler (C:\...\node_modules\awesome-typescript-loader\src\index.ts:35:45)
        at Object.loader (C:\...\node_modules\awesome-typescript-loader\src\index.ts:18:18)

windows 10
https://gist.github.com/gregbown/e7266bded1c5e5a3974f8df2222c821f

**Comment by vlasenko** [comment]
I had this issue and it was resolved by removing node_modules and reinstalling them again.
