### ISSUE TITLE
[Bug] "TypeError: Path must be a string" on nodejs 6 with tsconfig

### ISSUE THREAD

**Issue by Luchillo** [s-panferov/awesome-typescript-loader#255]
I'm having this error:

``` ts
 69% building modules 2033/2034 modules 1 active .../taoappionic2/src/theme/app.core.scssTypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1228:5)
    at Object.onRender (/home/carlos/Carlos/OSGroup/taoappionic2/node_modules/sass-loader/index.js:282:42)
    at Object.<anonymous> (/home/carlos/Carlos/OSGroup/taoappionic2/node_modules/sass-loader/node_modules/async/dist/async.js:2414:31)
    at apply (/home/carlos/Carlos/OSGroup/taoappionic2/node_modules/sass-loader/node_modules/async/dist/async.js:40:25)
    at Object.<anonymous> (/home/carlos/Carlos/OSGroup/taoappionic2/node_modules/sass-loader/node_modules/async/dist/async.js:76:12)
    at Object.callback (/home/carlos/Carlos/OSGroup/taoappionic2/node_modules/sass-loader/node_modules/async/dist/async.js:988:16)
    at options.success (/home/carlos/Carlos/OSGroup/taoappionic2/node_modules/node-sass/lib/index.js:309:32)
```

[This](https://github.com/s-panferov/awesome-typescript-loader/issues/134) issue has similar error but they have no tsconfig, i do have one:

``` json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "outFile": "./www",
    "paths": {
      "pages": [
        "./src/pages/index.ts"
      ],
      "components": [
        "./src/components/index.ts"
      ],
      "providers": [
        "./src/providers/index.ts"
      ],
      "pipes": [
        "./src/pipes/index.ts"
      ],
      "app.tao-animations": [
        "./src/theme/core/app.tao-animations.ts"
      ]
    },
    "lib": [
      "dom",
      "es6"
    ],
    "types": [
      "node",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "exclude": [
    "node_modules",
    "www"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}

```

**Comment by s-panferov** [comment]
Fixed in 3.x branch

**Comment by Luchillo** [comment]
Wow i had already forgotten this issue, it did fix after update.
