### ISSUE TITLE
3.0.0-beta.3 doesn't work with typescript@next

### ISSUE THREAD

**Issue by Hotell** [s-panferov/awesome-typescript-loader#282]
I'm using webpack 2.1.0 beta.25 but that's ok because it works with typescript@rc.
I need to use next so I can use [jsxFactory](https://github.com/Microsoft/TypeScript/issues/9582)

Error output:
```
TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/instance.ts:199:72)
    at Object.ensureInstance (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/instance.ts:104:5)
    at compiler (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/index.ts:36:20)
    at Object.loader (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/index.ts:15:18)
    at LOADER_EXECUTION (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at /Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/Users/hotell/Devel/labs/wc/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/hotell/Devel/labs/wc/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3) 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (/Users/hotell/Devel/labs/wc/node_module
s/awesome-typescript-loader/src/instance.ts:199:72)\n    at Object.ensureInstance (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/instance.ts:104:5)\n    at compi
ler (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/index.ts:36:20)\n    at Object.loader (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/
index.ts:15:18)\n    at LOADER_EXECUTION (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/hotell/Devel/labs/wc/node_modu
les/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /Users/hotell/Devel/l
abs/wc/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/Users/hotell/Devel/labs/wc/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    a
t /Users/hotell/Devel/labs/wc/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)'

[at-loader] Using typescript@2.2.0-dev.20161125 from typescript and "tsconfig.json" from /Users/hotell/Devel/labs/wc/tsconfig.json

TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/instance.ts:199:72)
    at Object.ensureInstance (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/instance.ts:104:5)
    at compiler (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/index.ts:36:20)
    at Object.loader (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/index.ts:15:18)
    at LOADER_EXECUTION (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at /Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/Users/hotell/Devel/labs/wc/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/hotell/Devel/labs/wc/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3) 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (/Users/hotell/Devel/labs/wc/node_module
s/awesome-typescript-loader/src/instance.ts:199:72)\n    at Object.ensureInstance (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/instance.ts:104:5)\n    at compi
ler (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/index.ts:36:20)\n    at Object.loader (/Users/hotell/Devel/labs/wc/node_modules/awesome-typescript-loader/src/
index.ts:15:18)\n    at LOADER_EXECUTION (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/hotell/Devel/labs/wc/node_modu
les/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/hotell/Devel/labs/wc/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /Users/hotell/Devel/l
abs/wc/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/Users/hotell/Devel/labs/wc/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    a
t /Users/hotell/Devel/labs/wc/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)'
```

**Comment by s-panferov** [comment]
Fixed by #281

**Comment by d-ph** [comment]
Hello @s-panferov . TS 2.1 has been released today and after upgrading I get the `Cannot read property 'exclude' of undefined` error. 

Could you tell me when you roughly plan to release awesome-typescript-helper v3, please?

**Comment by tkohr** [comment]
+1 we get the same error using TS 2.1 and awesome-typescript-loader 2.2.4. Any info on update would be great. Thanks!
