### ISSUE TITLE
Using some custom compilers breaks (e.g. scoped modules like @angular/tsc-wrapped)

### ISSUE THREAD

**Issue by jskrzypek** [s-panferov/awesome-typescript-loader#283]
### Error

```
> webpack --progress --profile --display-error-details --display-cached

Error: Cannot find module '/Users/jskrzypek/dev/ng2-webpack2-project/node_modules/@angular/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.setupTs (/Users/jskrzypek/dev/ng2-webpack2-project/node_modules/awesome-typescript-loader/src/instance.ts:150:29)
    at new PathsPlugin (/Users/jskrzypek/dev/ng2-webpack2-project/node_modules/awesome-typescript-loader/src/paths-plugin.ts:67:19)
    at Object.<anonymous> (/Users/jskrzypek/dev/ng2-webpack2-project/webpack.config.js:208:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/jskrzypek/dev/ng2-webpack2-project/node_modules/webpack/bin/convert-argv.js:98:18)
    at /Users/jskrzypek/dev/ng2-webpack2-project/node_modules/webpack/bin/convert-argv.js:111:17
    at Array.forEach (native)
    at module.exports (/Users/jskrzypek/dev/ng2-webpack2-project/node_modules/webpack/bin/convert-argv.js:109:15)
    at Object.<anonymous> (/Users/jskrzypek/dev/ng2-webpack2-project/node_modules/webpack/bin/webpack.js:141:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

### Diagnosis:

The error is coming from [these lines in `instance.setupTs()`](https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L149-L150): 
```ts
    const pkgPath = path.join(path.dirname(path.dirname(tsImplPath)), 'package.json');
    const compilerVersion = require(pkgPath).version;
```

The hardcoded number of `path.dirname()` calls works for some compiler modules (e.g. `typescript` and  `ntypescript` that use `./lib/typescript.js` or `./bin/ntypescript.js` for their entry path) but will break when the `compiler` config is a module with a different entry path. 

For example with `@angular/tsc-wrapped` or `@angular/compiler-cli`, the module's `package.entry` or `package.main` point to `'./index.js'` meaning that `path.join(path.dirname(path.dirname(tsImplPath)), 'package.json')` ends up pointing to my `node_modules/@angular/package.json` which does not exist, giving the error above.

**Comment by jskrzypek** [comment]
### Proposed fix: 
For my specific case I could add a check to see if the `compilerPath` is a scoped path (i.e. does it start with an `'@'` and does it contain a `'/'` or `'\'`?). However I think this may lead to the same problem of only accepting hard-coded subset of possibly intended compilers. 

I think the right solution will be a more general helper function that uses `fs.readdirSync()` to look for the nearest-neighbor `package.json` to the `tsImplPath` something like this:
```ts
function findTsImplPackage(inputPath: string) {
    let pkgDir = path.dirname(inputPath);
    if (fs.readdirSync(pkgDir).includes('package.json')) {
        return path.join(pkgDir, 'package.json');
    } else {
        return findTsImplPackage(pkgDir);
    }
}
```
