### ISSUE TITLE
fails with typescript 2.1.4

### ISSUE THREAD

**Issue by andrenarchy** [s-panferov/awesome-typescript-loader#293]
Updating from typescript 2.1.1 to 2.1.4 yields the following error:
```
TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at /home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/home/andre/git-repos/paperhive-frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /home/andre/git-repos/paperhive-frontend/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3) 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/instance.ts:266:72)\n    at Object.ensureInstance (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/instance.ts:145:5)\n    at compiler (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/home/andre/git-repos/paperhive-frontend/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /home/andre/git-repos/paperhive-frontend/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/home/andre/git-repos/paperhive-frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /home/andre/git-repos/paperhive-frontend/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)'
```

This is my tsconfig.json:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "types": ["node"]
  },
  "compileOnSave": false,
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by snerks** [comment]
Quick fix/hack:

Edit the following file:
~/node_modules/awesome-typescript-loader/dist/instance.js

Line ~142:
Replace the body of the "applyDefaults" method with the following:
function applyDefaults(configFilePath, compilerConfig, loaderConfig) {

`
    _.defaults(compilerConfig.options, {
        sourceMap: true,
        verbose: false,
        skipDefaultLibCheck: true,
        suppressOutputPathCheck: true
    });

    if (loaderConfig.transpileOnly) {
        compilerConfig.options.isolatedModules = true;
    }

    _.defaults(compilerConfig.options, {
        sourceRoot: compilerConfig.options.sourceMap ? process.cwd() : undefined
    });

    _.defaults(loaderConfig, {
        sourceMap: true,
        verbose: false,
    });

    delete compilerConfig.options.outDir;
    delete compilerConfig.options.inlineSourceMap;
    delete compilerConfig.options.outFile;
    delete compilerConfig.options.out;
    delete compilerConfig.options.noEmit;
`

**Comment by mduta** [comment]
Still not working with typescript 2.1.1

**Comment by s-panferov** [comment]
Which version of the loader this is related to?

**Comment by mduta** [comment]
3.10.8

**Comment by digital-wonderland** [comment]
This happens with 2.2.4

**Comment by selkinvitaly** [comment]
I have the same problem with typescript 2.0.3 and awesome-typescript-loader 2.2.4

**Comment by mduta** [comment]
i have the same problem with awesome-typescript-loader 3.10.8 and typescript 2.1.1 and 2.0.10

**Comment by bovan** [comment]
got it working here, had to lock down typescript version
```
{
    "awesome-typescript-loader": "^2.2.4",
    "typescript": "2.0.10"
}
```

**Comment by selkinvitaly** [comment]
It fine works with locked 2.0.3 typescript version

**Comment by sanyatuning** [comment]
working with typescript 2.1.1
but not working with typescript 2.1.4

**Comment by chrissena** [comment]
Using typescript 2.1.4 and awesome-typescript-loader version 2.2.4.
I had the same error
 `TypeError: Cannot read property 'exclude' of undefined`
Did the "Quick fix/hack" proposed by @snerks and can confirm my angular 2 app is working once more. Thanks!

**Comment by DanielMcAssey** [comment]
Same problem, pinned to Typescript 2.1.1 and it works.

**Comment by arjendeblok** [comment]
Version 2.1.4 renames typingOptions from compilerConfig to typeAcquisition. See PR https://github.com/Microsoft/TypeScript/pull/12373. So typingOptions is no longer available. So instance.js breaks on compilerConfig.typingOptions.exclude.

**Comment by aj0strow** [comment]
Works for me on beta.

```
    "awesome-typescript-loader": "3.0.0-beta.9",
    "typescript": "2.1.4",
```

**Comment by ribizli** [comment]
If it is only renaming some options (`Rename typingOptions.enableAutoDiscovery to typeAcquisition.enable`), could it be get fixed in the 2.4.x also, please?

**Comment by cgatian** [comment]
Since beta has issues with remapping code coverage, this would be ideal.

**Comment by heocon8319** [comment]
Fixed to me :  "awesome-typescript-loader": "2.2.4"
 "typescript": “2.1.1”

**Comment by roshan3133** [comment]
Its fixed with "typescript": "^2.1.4" and "awesome-typescript-loader": "^3.0.0-beta.9"
and working fine

**Comment by faddee** [comment]
What's the status? Object spread/rest is not working in 2.1.1. It would be nice to be able to upgrade and get rid of `Object.assign` and `delete` operators.

**Comment by cgatian** [comment]
@faddee I'm running 3.0.0-beta.17 and have no problems.

**Comment by faddee** [comment]
@cgatian Thanks, but I'm also suffering from #323 and `3.0.0-beta.13` still has this issue. So I'm stuck.

**Comment by ribizli** [comment]
We are also stuck to the 2.2 version, since 3.0's `TsConfigPathsPlugin` doesn't support webpack@2.2.

**Comment by Schnueggel** [comment]
still a problem :cry:

**Comment by pacoita** [comment]
Using version `awesome-typescript-loader 3.0.3` and `typescript 2.1.4` works. 

I faced this issue using awesome-typescript-loader 2.2.4 with typescript 2.1.4 (working though with typescript 2.0.10).

**Comment by kcsahoo** [comment]
In tsconfig.json, I configured the following:
"awesomeTypescriptLoaderOptions": {
"useWebpackText": true,
"useTranspileModule": true,
"doTypeCheck": true,
"forkChecker": true
},

Then I am able use ATL 3.2.1 and Typescript 2.2.1
No errors.

**Comment by paigeflourin** [comment]
had error using awesome-typescript-loader 2.2.4 and typescript 2.0.10

fixed with @snerks quick fix.

**Comment by dksharp** [comment]
Nothing worked. tried everything in this thread :(

`ERROR` in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main

ERROR in ./src/vendor.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi vendor
webpack: Failed to compile.`

**Comment by DenisVuyka** [comment]
We gave up waiting months and switched to `ts-loader`, that solved all the issues we have with this project.

**Comment by dksharp** [comment]
@DenisVuyka can you guide me please.

**Comment by DenisVuyka** [comment]
@dksharp You can refer to the [official webpack guide](https://webpack.js.org/guides/typescript/) for TypeScript that is now featuring `ts-loader`:

**Comment by s-panferov** [comment]
`awesome-typescript-loader@2.x` is not maintained. Please use 3.x branch or switch to `ts-loader` if you can't.

**Comment by RafaelSobreiraBraga** [comment]
```
"awesome-typescript-loader": "^3.0.3",
"typescript": "^2.4.1",
"webpack": "^1.13.0",
"webpack-dev-server": "^1.14.1",
"webpack-merge": "^0.14.0"
```
It's working.

**Comment by ramseyjiang** [comment]
@RafaelSobreiraBraga 
"awesome-typescript-loader": "^3.0.3",
    "typescript": "^2.4.1",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"

The issue still there.

**Comment by Thorocaine** [comment]
I am having this problem.
typescript: 2.6.2
awesome-typescript-loader: 3.4.0
