### ISSUE TITLE
Error when using .tsx files

### ISSUE THREAD

**Issue by mikemorton** [s-panferov/awesome-typescript-loader#30]
Please forgive me if I'm missing something obvious here:

main.ts: 
```
/// <reference path='..\typings/react/react.d.ts' />
import React = require('react');
import temp = require('./components/uitest');
React.render(React.createElement(temp), document.getElementById('content'));
```
components\uitest.tsx:
```
/// <reference path="../../typings/react/react.d.ts" />
import * as React from 'react';
class MyComponent extends React.Component<any, any>
{
    render() {
        return <div>asdf</div>;
    }
}
export = MyComponent;
```

tsconfig.json:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "listFiles": true,
        "jsx": "react"
    },
    "awesomeTypescriptLoaderOptions": {
        "compiler": "ntypescript"
    }
}
```

webpack.config.js:
```
var path = require('path');
module.exports = {
    entry: path.resolve(__dirname, 'app/main.ts'),
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'bundle.js',
    },
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.tsx',  '.ts', '.js']
    },
    module: {
        loaders: [
            {
                test: /\.ts(x?)$/,
                loader: 'awesome-typescript-loader'
            }
        ]
    }
};
```
Output from `npm run build` which simply calls webpack:
```
C:\MyProject\Reactor\Reactor>npm run build

> Reactor@0.0.0 build C:\MyProject\Reactor\Reactor
> webpack

Hash: 04f068e1dbdc71d85fd4
Version: webpack 1.10.1
Time: 1654ms
    Asset    Size  Chunks             Chunk Names
bundle.js  635 kB       0  [emitted]  main
    + 158 hidden modules

ERROR in ./app/components/uitest.tsx
Module build failed: Error: File C:/MyProject/Reactor/Reactor/app/components/uitest.tsx was not found in program
    at State.emit (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\dist\host.js:101:23)
    at C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\dist\index.js:208:22
    at tryCatcher (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\promis
e.js:489:31)
    at Promise._settlePromiseAt (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\promise.js:565:
18)
    at Async._drainQueue (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (C:\MyProject\Reactor\Reactor\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:415:13)
 @ ./app/main.ts 3:11-41

ERROR in
File 'C:/MyProject/Reactor/Reactor/app/components/uitest.tsx' must have extension '.ts' or '.d.ts'.

ERROR in C:/MyProject/Reactor/Reactor/app/main.ts:5:22
Cannot find external module './components/uitest'.
```
If I simply run ntsc it compiles correctly without issue, FWIW

**Comment by mikemorton** [comment]
I narrowed this down a little bit.  The first problem I found was that my txconfig.json file was not being parsed until after the compiler had been determined using the query parameters to the 'loader' option in the webpack.config.js.  So it was still using the original typescript instead of ntypescript.  I changed it to `loader: 'awesome-typescript-loader?compiler=ntypescript&jsx=react&module=commonjs'` and things progressed a little further.

Now my problem is that I get the following error: `Error: no output found for C:\MyProject\Reactor\Reactor\app\components\uitest.tsx`

It seems this is happening because `findResultFor ` in helpers doesn't have any way of accounting for tsx files.

**Comment by s-panferov** [comment]
@mikemorton I'll at this problem tomorrow morning (GMT+3)

**Comment by s-panferov** [comment]
@mikemorton JSX support was published as v0.6.0. Please look at the [example](https://github.com/s-panferov/awesome-typescript-loader/tree/master/examples/tsx).

Also note that there is a bug with source-maps right now, I've sent the [PR](https://github.com/babel/babel-loader/pull/85) to the babel-loader to fix it.

**Comment by mikemorton** [comment]
Awesome, thanks.  I'll give this a test later day!

**Comment by s-panferov** [comment]
@mikemorton ping

**Comment by mikemorton** [comment]
Sorry, I didn't get a chance to try it out yesterday but I hope to again today...

**Comment by s-panferov** [comment]
@mikemorton I've tested this enough in my company to say that is works. So I close this. Feel free to reopen the issue if you find some troubles.
