### ISSUE TITLE
Multiple bundler call emit error `channel closed`

### ISSUE THREAD

**Issue by Delagen** [s-panferov/awesome-typescript-loader#304]
webpack.run second call on the same instance emit 
```
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at Object.send (...\node_modules\awesome-typescript-loader\src\checker\send.ts:24:35)
    at Checker.req (...\node_modules\awesome-typescript-loader\src\checker\checker.ts:87:21)
    at Checker.emitFile (...\node_modules\awesome-typescript-loader\src\checker\checker.ts:98:21)
    at transform (...\node_modules\awesome-typescript-loader\src\index.ts:107:29)
    at transformationFunction (...\node_modules\awesome-typescript-loader\src\index.ts:58:44)
    at compiler (...\node_modules\awesome-typescript-loader\src\index.ts:74:30)
    at Object.loader (...\node_modules\awesome-typescript-loader\src\index.ts:16:18)
    at LOADER_EXECUTION (...\node_modules\loader-runner\lib\LoaderRunner.js:114:14)
    at runSyncOrAsync (...\node_modules\loader-runner\lib\LoaderRunner.js:115:4)
    at iterateNormalLoaders (...\node_modules\loader-runner\lib\LoaderRunner.js:224:2)
    at ...\node_modules\loader-runner\lib\LoaderRunner.js:197:4
    at Storage.finished (...\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:39:16)
    at ...\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)

```

**Comment by s-panferov** [comment]
@Delagen please provide some more info about your environment and configuration.

**Comment by Delagen** [comment]
```
var webpack = require("webpack");
var bundler = webpack(webpackConfig);

bundler.run(function(bundlerErr, stats) {});

//some time later

bundler.run(function(bundlerErr, stats) {});

```

**Comment by s-panferov** [comment]
@Delagen ah, I see. You don't use `watch`, but call run several times. Loader kills subprocess after the first `run` because of this https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L390

**Comment by Delagen** [comment]
@s-panferov All works till beta 9, and on 2.x versions

**Comment by grantbowering** [comment]
@s-panferov, trying to load CheckerPlugin in the plugins sections of my webpack.config.js as per the documentation crashes my watch immediately with the following stacktrace:
```
TypeError: Cannot read property 'parentCompilation' of undefined
    at getRootCompiler ([...]\node_modules\awesome-typescript-loader\src\instance.ts:50:17)
    at ensureInstanceStore ([...]\node_modules\awesome-typescript-loader\src\instance.ts:67:24)
    at Object.ensureInstance ([...]\node_modules\awesome-typescript-loader\src\instance.ts:90:5)
    at compiler ([...]\node_modules\awesome-typescript-loader\src\index.ts:42:20)
    at new loader ([...]\node_modules\awesome-typescript-loader\src\index.ts:16:18)
    at Object.<anonymous> ([...]\webpack.config.js:79:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
I have a couple other plugins loaded so it might be a piping issue?  I tried placing CheckerPlugin at either end of the plugins list and had the same result in both orders.
```js
plugins: [
	new CheckerPlugin(),
	// Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
	new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }),
	new ProgressPlugin(progressHandler)
],
```

**Comment by Izhaki** [comment]
I'm having the same issue, and also suspect it has to do with other plugins.

```
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Object.send (/Volumes/Data/Development/Sites/majorgenerator/node_modules/awesome-typescript-loader/src/checker/send.ts:46:26)
    at Checker.req (/Volumes/Data/Development/Sites/majorgenerator/node_modules/awesome-typescript-loader/src/checker/checker.ts:101:21)
    at Checker.updateFile (/Volumes/Data/Development/Sites/majorgenerator/node_modules/awesome-typescript-loader/src/checker/checker.ts:116:21)
    at /Volumes/Data/Development/Sites/majorgenerator/node_modules/awesome-typescript-loader/src/instance.ts:398:29
    at Array.map (native)
    at Compiler.<anonymous> (/Volumes/Data/Development/Sites/majorgenerator/node_modules/awesome-typescript-loader/src/instance.ts:395:14)
    at next (/Volumes/Data/Development/Sites/majorgenerator/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.compiler.plugin (/Volumes/Data/Development/Sites/majorgenerator/node_modules/webpack/lib/CachePlugin.js:32:5)
    at next (/Volumes/Data/Development/Sites/majorgenerator/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/Volumes/Data/Development/Sites/majorgenerator/node_modules/awesome-typescript-loader/src/watch-mode.ts:12:13)
    at Compiler.applyPluginsAsyncSeries (/Volumes/Data/Development/Sites/majorgenerator/node_modules/tapable/lib/Tapable.js:142:13)
    at Watching._go (/Volumes/Data/Development/Sites/majorgenerator/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.invalidate (/Volumes/Data/Development/Sites/majorgenerator/node_modules/webpack/lib/Compiler.js:132:8)
    at Watching.<anonymous> (/Volumes/Data/Development/Sites/majorgenerator/node_modules/webpack/lib/Compiler.js:116:8)
    at EventEmitter.watcher.once (/Volumes/Data/Development/Sites/majorgenerator/node_modules/webpack/lib/node/NodeWatchFileSystem.js:45:4)
    at EventEmitter.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (/Volumes/Data/Development/Sites/majorgenerator/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

And the webpack config:
```js
    plugins: [
        new CheckerPlugin(),
        new NodemonPlugin(),
    ],
```
Worth noting that `NoemonPlugin()` also spawns child processes.
