### ISSUE TITLE
Module Build failure with beta 3.0.0-beta.13

### ISSUE THREAD

**Issue by karptonite** [s-panferov/awesome-typescript-loader#307]
I'm just trying to move to beta 3, so I can't say if this applies to previous betas. It is likely a config error on my part, but I don't see the problem.

My config is here:
https://gist.github.com/karptonite/20b64370efe812d266104f30c629f9cb
Apologies for the indentation!

Using typescript 2.1.1. I get the following error:
```
ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at /Users/karp/Documents/git/bgg/geekui2/node_modules/awesome-typescript-loader/src/index.ts:82:28
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ multi polyfills
```
I get that for each entry file. Works fine in 2.2.4, with the only difference being that the CheckerPlugin isn't loaded/included.

**Comment by s-panferov** [comment]
Do you use cache? Does `rm -rf .awcache` helps?

**Comment by karptonite** [comment]
Yes, that seems to have solved the problem (clearing the cache dir that i specify in tsconfig). Maybe saving off the loader version and config hashes in a file in the cache, and auto-wiping it if that changes, might prevent this problem for other users?

**Comment by msc117** [comment]
I was having the same issue, `rm -rf .awcache` resolves that for me. Thanks

**Comment by pselden** [comment]
Note: this plugin uses the hashing approach for its cache: https://github.com/mzgoddard/hard-source-webpack-plugin
