### ISSUE TITLE
When use a empty xxx.d.ts,at-loader will throw an exception

### ISSUE THREAD

**Issue by hstarorg** [s-panferov/awesome-typescript-loader#320]
Maybe it is typescript bug.

**Comment by rcollette** [comment]
I can't speak to the latest beta version, but but prior versions add an "opinion" that generated empty files are in some way a bug whereas the tsc compiler does not.   I don't know if this is related.

I would suggest that in the upcoming version, such added behavior not be included.   If tsc doesn't consider it an error, why should a loader.

Our older gulp builds used to filter out interface only files (.I.js) because they would be empty.   Such an option for empty output files would be welcome, since we have little other control, to my knowledge, of file handling in a manner similar to a gulp pipeline.

**Comment by hstarorg** [comment]
Some error info:
```
ERROR in ./src/modules/nk-demo/index.ts
Module build failed: Error: Final loader didn't return a Buffer or String
    at D:\TeamCode\newkit\node_modules\webpack\lib\NormalModule.js:151:64
    at D:\TeamCode\newkit\node_modules\loader-runner\lib\LoaderRunner.js:365:3
    at iterateNormalLoaders (D:\TeamCode\newkit\node_modules\loader-runner\lib\LoaderRunner.js:206:10)
    at iterateNormalLoaders (D:\TeamCode\newkit\node_modules\loader-runner\lib\LoaderRunner.js:213:10)
    at D:\TeamCode\newkit\node_modules\loader-runner\lib\LoaderRunner.js:228:3
    at context.callback (D:\TeamCode\newkit\node_modules\loader-runner\lib\LoaderRunner.js:106:13)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
The empty file is created by myself. It's not a common case.
In the version 3.0.0-beta.17, the same problem.

**Comment by hstarorg** [comment]
set content 
```
export {};
```
to the empty xx.d.ts, will shy away this problem.

**Comment by claudiuconstantin** [comment]
I am  also encountering this error:

```
ERROR in ./test/test2/test3/file.ts
Module build failed: Error: Final loader didn't return a Buffer or String
[...]
```
with the following package versions:

```
"devDependencies": {
 [...]
 "awesome-typescript-loader": "^3.0.3",
 "typescript": "^2.1.0",
 "webpack": "^2.2.1",
 [...]
}
```
Any ideas why this is happening?

**Comment by hstarorg** [comment]
@claudiuconstantin  some d.ts is empty will throw the messages.

**Comment by s-panferov** [comment]
Could anyone make a repro please? I can't reproduce this.

**Comment by s-panferov** [comment]
It seems to be a bug in TypeScript

**Comment by s-panferov** [comment]
I've finally understood what is going on. Please confirm my thoughts.

*Repro case:*

**index.ts**: 
```
import './empty.d.ts'
```

This will be transpiled by typescript into:

**index.js**: 
```
require('./empty.d.ts')
```

Then webpack tries to load `index.d.ts` with `atl`, because it has `.ts` extension. But loader can't emit `.d.ts`, this is no-op.

I'll make a hack in the loader to emit empty modules in such cases, but actually, this should never happen, because `import './empty.d.ts'` should instead be written as `import './empty'`;

**Comment by alimazrooei** [comment]
I have the same issue please help me(urgent)
