### ISSUE TITLE
[3.0.0-beta.17] Incompatible with webpack.OldWatchingPlugin

### ISSUE THREAD

**Issue by mekwall** [s-panferov/awesome-typescript-loader#331]
When using `webpack.OldWatchingPlugin` at-loader will throw the following error after a save:

```
xxx\node_modules\awesome-typescript-loader\src\instance.ts:303
        const watcher = watching.compiler.watchFileSystem.watcher || watching.compiler.watchFileSystem.wfs.watcher;

                    ^
TypeError: Cannot read property 'watcher' of undefined
    at Compiler.<anonymous> (xxx\node_modules\awesome-typescript-loader\src\instance.ts:303:107)
    at Compiler.next (xxx\node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:14)
    at Compiler.invalidAsyncPlugin (xxx\node_modules\webpack-dev-middleware\middleware.js:80:3)
    at Compiler.next (xxx\node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:14)
    at Compiler.<anonymous> (xxx\node_modules\awesome-typescript-loader\src\watch-mode.ts:12:13)
    at Compiler.applyPluginsAsync (xxx\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:13)
    at Watching._go (xxx\node_modules\webpack\lib\Compiler.js:44:16)
    at Watching.invalidate (xxx\node_modules\webpack\lib\Compiler.js:108:8)
    at Watching.<anonymous> (xxx\node_modules\webpack\lib\Compiler.js:93:8)
    at Timeout.onTimeout [as _onTimeout] (xxx\node_modules\webpack\lib\node\OldNodeWatchFileSystem.js:234:3)
```

Addendum: ts-loader had the [same issue](https://github.com/TypeStrong/ts-loader/issues/155) and it was [fixed](https://github.com/TypeStrong/ts-loader/pull/167). Working on a pull request.

**Comment by s-panferov** [comment]
@mekwall why do you need this?

**Comment by mekwall** [comment]
@s-panferov because some of our devs have to use `webpack.OldWatchingPlugin` to have webpack trigger properly on changed files

**Comment by mekwall** [comment]
No longer necessary for us so closing this.
