### ISSUE TITLE
v3.0.5 broken (possibly related to loader-utils)

### ISSUE THREAD

**Issue by JamesGuthrie** [s-panferov/awesome-typescript-loader#377]
Sorry about the title not being very descriptive. It appears as though the following commit has broken atl for our usage: https://github.com/s-panferov/awesome-typescript-loader/commit/9fbc5b3270e1418a2c116df0a1b3c7f74de1c629

The error I'm getting is:

`TypeError: Cannot read property 'instance' of null
    at compiler (<project root>/node_modules/awesome-typescript-loader/src/index.ts:44:31)
    at Object.loader (<project root>/node_modules/awesome-typescript-loader/src/index.ts:14:18)
    at WEBPACK_CORE_LOADER_EXECUTION (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at <project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.module.exports (<project root>/node_modules/tslint-loader/index.js:112:3)
    at WEBPACK_CORE_LOADER_EXECUTION (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (<project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at <project root>/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (<project root>/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at <project root>/node_modules/graceful-fs/graceful-fs.js:78:16`

**Comment by Prior99** [comment]
I have the exact same problem.

**Comment by Prior99** [comment]
For now I will work around this issue by fixing awesome-typescript-loader to version 3.0.4 by setting 

```
"awesome-typescript-loader": "=3.0.4",
```

in my package.json, however this is not really a solution to this problem. Is there something I can change in my webpack config to work around this?

I had a look at https://github.com/webpack/loader-utils/issues/56 and tried changing `options` to `query` but without any results. I would rather not go back to configuring my rules using the old query `?option=value` syntax.

**Comment by dweber019** [comment]
I fixed this by always providing a option to the loader even if it's an empty object like this `{}`.

If you are using https://github.com/easy-webpack/config-typescript then pass option like this:
`require('@easy-webpack/config-typescript')({options: {}})`
