### ISSUE TITLE
awesome-typescript-loader crashes with typescript 2.3.2 when compiling JS files with allowJS

### ISSUE THREAD

**Issue by trodrigues** [s-panferov/awesome-typescript-loader#424]
I recently added Typescript to a project which I intend to convert over time but which is still entirely composed of `.js` files (no `.ts` or `.tsx` files at all yet). I used awesome-typescript-loader together with babel-loader as shown in https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html with some tweaks in the config to have TS output ES modules and have those being compiled by babel itself (due to some modules not having a proper default export, but that's another story).

This worked fine with Typescript 2.2.*, but with the recent release of Typescript 2.3, the following started happening:

```
% npm run start

> atl-test-case@0.1.0 start /Users/trodrigues/atl-test-case
> NODE_ENV=development webpack-dev-server

Project is running at http://0.0.0.0:3010/
webpack output is served from /build/js/

[at-loader] Using typescript@2.3.2 from typescript and "tsconfig.json" from /Users/trodrigues/atl-test-case/tsconfig.json.

[at-loader]: Child process failed to process the request:  RangeError: Maximum call stack size exceeded
    at checkIdentifier (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:36148:33)
    at checkExpressionWorker (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:41135:28)
    at checkExpression (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:41115:42)
    at checkExpressionWithContextualType (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:40983:26)
    at checkApplicableSignature (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:38813:35)
    at chooseOverload (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:39316:30)
    at resolveCall (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:39220:26)
    at resolveNewExpression (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:39482:33)
    at resolveSignature (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:39639:28)
    at getResolvedSignature (/Users/trodrigues/atl-test-case/node_modules/typescript/lib/typescript.js:39669:26)

[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.058 sec.
Hash: 19c007a05531681a8339
Version: webpack 2.4.1
Time: 11668ms
        Asset    Size  Chunks                    Chunk Names
    loader.js  303 kB       0  [emitted]  [big]  loader
loader.js.map  574 kB       0  [emitted]         loader
chunk    {0} loader.js, loader.js.map (loader) 291 kB [entry] [rendered]
   [26] (webpack)-dev-server/client?http://0.0.0.0:3010 6.42 kB {0} [built]
   [27] ./app.js 80 bytes {0} [built]
   [28] ./~/ansi-html/index.js 4.71 kB {0} [built]
   [31] ./~/events/events.js 9.28 kB {0} [built]
   [32] ./~/html-entities/index.js 245 bytes {0} [built]
   [36] ./~/punycode/punycode.js 17.5 kB {0} [built]
   [39] ./~/querystring-es3/index.js 129 bytes {0} [built]
   [41] ./~/sockjs-client/lib/entry.js 250 bytes {0} [built]
   [60] ./~/strip-ansi/index.js 168 bytes {0} [built]
   [63] ./~/url/url.js 26.2 kB {0} [built]
   [64] ./~/url/util.js 366 bytes {0} [built]
   [65] (webpack)-dev-server/client/overlay.js 4.03 kB {0} [built]
   [66] (webpack)-dev-server/client/socket.js 1.05 kB {0} [built]
   [67] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [69] multi (webpack)-dev-server/client?http://0.0.0.0:3010 ./app.js 40 bytes {0} [built]
     + 55 hidden modules

ERROR in ./~/sockjs-client/lib/main.js
Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (/Users/trodrigues/atl-test-case/node_modules/webpack/lib/NormalModule.js:201:46)
    at /Users/trodrigues/atl-test-case/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/trodrigues/atl-test-case/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/trodrigues/atl-test-case/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/trodrigues/atl-test-case/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/trodrigues/atl-test-case/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./~/sockjs-client/lib/entry.js 3:17-34
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://0.0.0.0:3010
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3010 ./app.js
webpack: Failed to compile.
```
I've created a reduced test case out of my project where the issue can be reproduced at https://github.com/trodrigues/atl-test-case

I've kept the same options in the `tsconfig.json` file and kept the webpack config as close as possible, and the problem still occurs.

I had initially opened an [issue](https://github.com/Microsoft/TypeScript/issues/15551) in the typescript repo, and they asked if this happened when running `tsc` just by itself, and it doesn't. The files compile properly, and get output into the `build` directory. The issue only occurs when using it with `awesome-typescript-loader`.

Let me know if I can provide any more details.

**Comment by justrhysism** [comment]
I'm getting the same error with `"allowJs": false`.

I am however, consuming modules which are JS.

**Comment by justrhysism** [comment]
Actually, never mind. I have since discovered that whilst refactoring, I had somehow created a circular import loop. 

 :confounded: _Carry on..._

**Comment by etse** [comment]
I get the same issue in my repository. When I let atl compile JS-fils it throws the above error. If I only let it transpile typescript, and ship javascript to babel-loader my project builds fine.

**Comment by s-panferov** [comment]
Should work in the latest loader

**Comment by JSMike** [comment]
This is still happening for me with awesome-typescript-loader@3.2.2 and typescript@2.3.4
