### ISSUE TITLE
loaderUtils.parseQuery() received a non-string value which can be problematic

### ISSUE THREAD

**Issue by skorunka** [s-panferov/awesome-typescript-loader#425]
See see https://github.com/webpack/loader-utils/issues/56

```
(node:20484) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\ng-router-loader\node_modules\loader-utils\index.js:78:3)
    at Loader.replace (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\src\Loader.ts:61:67)
    at Object.loader (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\index.ts:13:7)
    at LOADER_EXECUTION (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at iterateNormalLoaders (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Projects\Solutions\Anticipate\src\Eyc.Solutions.Anticipate.Ui.Web\node_modules\awesome-typescript-loader\src\index.ts:106:13
```

Replace parseQuery() with a getOptions() in awesome-typescript-loader\src\index.ts:106:13

**Comment by s-panferov** [comment]
done

**Comment by skorunka** [comment]
Thank you.
