### ISSUE TITLE
TsConfigPathsPlugin - Cannot read property 'parentCompilation' of undefined

### ISSUE THREAD

**Issue by Bradleycorn** [s-panferov/awesome-typescript-loader#433]
Trying to use TsConfigPathsPlugin per the Readme, and I'm getting the following error:

```
TypeError: Cannot read property 'parentCompilation' of undefined
    at Object.getRootCompiler (/Users/brad.ball/dev/projects/webpack/node_modules/awesome-typescript-loader/src/instance.ts:54:17)
    at compiler (/Users/brad.ball/dev/projects/webpack/node_modules/awesome-typescript-loader/src/index.ts:42:26)
    at new loader (/Users/brad.ball/dev/projects/webpack/node_modules/awesome-typescript-loader/src/index.ts:16:18)
...
```

Relevant parts of my webpack.config:
```
var  TsConfigPathsPlugin  = require('awesome-typescript-loader');


module.exports = {
    module: {
        rules: [

            {
                test: /\.ts$/,
                loaders: [
                    {
                        loader: 'awesome-typescript-loader'
                    },
                    'angular2-template-loader'
                ]
            }
```
```
    plugins: [
        new TsConfigPathsPlugin({
            configFileName: "tsconfig.json",
            compiler: "typescript"
        }),

    ]
```
Environment:
awesome-typescript-loader: 3.1.3
typescript: 2.3.2
webpack: 2.5.1

**Comment by s-panferov** [comment]
Please create a repro case

**Comment by theBull** [comment]
@Bradleycorn FYI `configFileName: tsconfig.json` and `compiler: "typescript"` are default values, so you don't need to pass them into the constructor.
