### ISSUE TITLE
Compatibility with typescript 2.4

### ISSUE THREAD

**Issue by rapilabs** [s-panferov/awesome-typescript-loader#440]
Attempting to use `awesome-typescript-loader` with `typescript` `2.4` resulted in:

```
ERROR in ./src/main.tsx
Module build failed: TypeError: Cannot read property 'fileExists' of undefined
    at readConfigFile (/path/to/project/node_modules/awesome-typescript-loader/src/instance.ts:291:67)
    at Object.ensureInstance (/path/to/project/node_modules/awesome-typescript-loader/src/instance.ts:95:9)
    at compiler (/path/to/project/node_modules/awesome-typescript-loader/src/index.ts:47:22)
    at Object.loader (/path/to/project/node_modules/awesome-typescript-loader/src/index.ts:16:18)
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/main.tsx
webpack: Failed to compile.
```

**Comment by s-panferov** [comment]
My tests passes with typescript@2.4. Please provide more details or a repro case.
