### ISSUE TITLE
postinstall for 4.0.0-0 requires husky

### ISSUE THREAD

**Issue by daniel-white** [s-panferov/awesome-typescript-loader#543]
I'm trying to upgrade to 4.0.0-0 on Windows and husky is failing when running.

```
>npm install --save awesome-typescript-loader@next

> awesome-typescript-loader@4.0.0-0 postinstall addin\node_modules\awesome-typescript-loader
> node node_modules/husky/bin/install.js || true

module.js:559
    throw err;
    ^

Error: Cannot find module 'addin\node_modules\awesome-typescript-loader\node_modules\husky\bin\install.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
'true' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by s-panferov** [comment]
Ooops
