### ISSUE TITLE
Error installing on macOS

### ISSUE THREAD

**Issue by SebTM** [s-panferov/awesome-typescript-loader#552]
Hello,

I wanted to install awesome-typescript-loader (@next) for using with webpack 4. After installation it calls "awesome-typescript-loader@4.0.0-0 postinstall" which executes "node node_modules/husky/bin/install.js || true"

```
> fsevents@1.1.3 install /node_modules/fsevents
> node install

[fsevents] Success: "/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> node-sass@4.7.2 install /node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/ssellmeier/.npm/node-sass/4.7.2/darwin-x64-59_binding.node

> awesome-typescript-loader@4.0.0-0 postinstall /node_modules/awesome-typescript-loader
> node node_modules/husky/bin/install.js || true

module.js:545
    throw err;
    ^

Error: Cannot find module '/node_modules/awesome-typescript-loader/node_modules/husky/bin/install.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

> node-sass@4.7.2 postinstall /node_modules/node-sass
> node scripts/build.js

Binary found at /node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine

> styled-components@3.2.1 postinstall /node_modules/styled-components
> opencollective postinstall


                    Thanks for installing styled-components 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 183
                              Number of backers: 15
                              Annual budget: US$ 887
                             Current balance: US$ 545

     👉  Donate: https://opencollective.com/styled-components/donate

added 1458 packages in 23.091s

```

**Comment by s-panferov** [comment]
This issue is already fixed in both 4.x and 5.x releases
