### ISSUE TITLE
Webpack 4: DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by blacksonic** [s-panferov/awesome-typescript-loader#558]
When using the loader with Webpack 4 I get this error message: `DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead`. It works, but always show deprecation message.

The corresponding stack trace:
```
(node:55845) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at setupWatchRun (/Users/home/node_modules/awesome-typescript-loader/src/instance.ts:367:11)
    at Object.ensureInstance (/Users/home/node_modules/awesome-typescript-loader/src/instance.ts:135:2)
    at compiler (/Users/home/node_modules/awesome-typescript-loader/src/index.ts:47:19)
    at Object.loader (/Users/home/node_modules/awesome-typescript-loader/src/index.ts:16:12)
    at LOADER_EXECUTION (/Users/home/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/home/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/home/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/home/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/home/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/home/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/home/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:513:3)
```

You can print out the stack trace with `node --trace-deprecation ./node_modules/.bin/webpack`.

**Comment by grzegorzjudas** [comment]
Yup, new webpack changed the APIs:

https://github.com/jantimon/html-webpack-plugin/issues/874

**Comment by thescientist13** [comment]
seems like this would be solved as part of an upgrade to #534

**Comment by waspar** [comment]
Still have this warning 
node v8.14.1
webpack v4.29.2
