### ISSUE TITLE
[at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'externalModuleIndicator' of undefined

### ISSUE THREAD

**Issue by WingGao** [s-panferov/awesome-typescript-loader#561]
at version 4.0.1, ts version 2.7.2
log message:
```
[at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (/Users/user/Projs/mpvue-ts-demo/node_modules/typescript/lib/typescript.js:13733:21)
    at Object.getAllDependencies (/Users/user/Projs/mpvue-ts-demo/node_modules/typescript/lib/typescript.js:75788:46)
    at Object.getAllDependencies (/Users/user/Projs/mpvue-ts-demo/node_modules/typescript/lib/typescript.js:76133:80)
    at processEmit (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/checker/runtime.ts:451:24)
    at /Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/checker/runtime.ts:602:6
    at Object.send (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/checker/runtime.ts:48:6)
    at Checker.req (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/checker/checker.ts:100:15)
    at Checker.emitFile (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/checker/checker.ts:105:15)
    at transform (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/index.ts:132:26)
    at transformationFunction (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/index.ts:74:40)
    at Object.cache (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/cache.ts:104:10)
    at compiler (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/index.ts:77:21)
    at Object.loader (/Users/user/Projs/mpvue-ts-demo/node_modules/awesome-typescript-loader/src/index.ts:16:12)
    at LOADER_EXECUTION (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at Object.context.callback (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/user/Projs/mpvue-ts-demo/node_modules/mpvue-loader/lib/selector.js:21:8)
    at LOADER_EXECUTION (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/user/Projs/mpvue-ts-demo/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
```

When loader try to load an empty file.
```ts
	function processEmit({ seq, payload }: EmitFile.Request) {
		updateFile(payload.fileName, payload.text)
		const emitResult = emit(payload.fileName)
		const program = getProgram()
		const sourceFile = program.getSourceFile(payload.fileName) //fileName = '', then sourceFile = null
		const deps = program.getAllDependencies(sourceFile) // error

		replyOk(seq, { emitResult, deps })
	}
```

**Comment by raoulnair** [comment]
I am also getting same issue but only while running unit test. I have raised issue for the same in stackoverflow [more details](https://stackoverflow.com/questions/49468616/cannot-read-property-externalmoduleindicator-of-undefined-while-running-unit-t)

**Comment by subramn** [comment]
I am also seeing the same issue any temporary fix?

**Comment by L0stSoul** [comment]
Same problem here :C

**Comment by lilijialiang** [comment]
same problem :(

**Comment by Wtango** [comment]
Same problem, any update?

**Comment by oychao** [comment]
same problem here.

**Comment by BiosBoy** [comment]
same problem (

**Comment by ramuda** [comment]
Any updates on this issue? whenever I upgrade to webpack 4 and awesome typescript loader to 5.x this issue is replicated. I am using typescript 2.7.1

**Comment by smonette** [comment]
Same problem!

**Comment by goloveychuk** [comment]
`allowJs` should help
