### ISSUE TITLE
vue.js compiling single file component

### ISSUE THREAD

**Issue by rx-837** [s-panferov/awesome-typescript-loader#564]
I have the error when compile single file component *.vue, contains <script lang="ts">{{ TS_CODE_HERE }}</script>

```
ERROR in ./node_modules/awesome-typescript-loader/dist/entry.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloDecorator.vue
Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (/project/TypeScript-Vue-Starter/node_modules/webpack/lib/NormalModule.js:256:7)
    at /project/TypeScript-Vue-Starter/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/project/TypeScript-Vue-Starter/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/project/TypeScript-Vue-Starter/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /project/TypeScript-Vue-Starter/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/project/TypeScript-Vue-Starter/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./src/components/HelloDecorator.vue 7:0-127 7:0-127 8:0-140 21:2-16
 @ ./src/index.ts
```

Project: https://github.com/Microsoft/TypeScript-Vue-Starter

1) replaced values at package.json: 

```
"dependencies": {
    "vue": "^2.5.16",
    "vue-class-component": "^6.2.0",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "awesome-typescript-loader": "^5.0.0-0",
    "css-loader": "^0.28.11",
    "ts-loader": "^4.1.0",
    "typescript": "2.7.2",
    "vue-loader": "^14.2.2",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.4.1",
    "webpack-cli": "^2.0.13"
  } 
```

2) at webpack.config.js replace `ts-loader` to `awesome-typescript-loader`

**Comment by araynimax** [comment]
Did you find a solution? I've got the same problem
