### ISSUE TITLE
Exporting types results in incomplete d.ts output

### ISSUE THREAD

**Issue by quantuminformation** [s-panferov/awesome-typescript-loader#566]
In this library [file](https://github.com/quantumjs/solar-popup/blob/master/src/index.ts#L1) I am Reexporting a `type` from vanilla-typescript so that the end user of solar-popup doesn't need to install vanilla-typescript.

However in the build folder I am missing several definiton files.
<img width="1073" alt="screen shot 2018-04-04 at 12 57 29" src="https://user-images.githubusercontent.com/216566/38307035-4c892e70-380a-11e8-90d9-3e81608e9b3f.png">

Any ideas?

**Comment by QuantumInformation** [comment]
Hmm, after looking at this it seems that exporting types is legal code, but doesn't produce any output in the d.ts

```js
// When you have optional parts
export type OptionalDimensions = {
  width?: number,
  height?: number
}
```

**Comment by pachuka** [comment]
I'm running into the same issue with awesome-typescript-loader 5.0.0.

type ITest = { themeId: string };

export { ITest};

results in no output with awesome-typescript-loader. Does emit a proper d.ts using ts-loader.

Thanks!

**Comment by QuantumInformation** [comment]
I'd prefer not to use ts-loader as it bhaves differently, eg if I replace my project with it I get this error which I don't with Awesome


ERROR in ./node_modules/vanilla-typescript/index.ts
Module build failed: Error: Typescript emitted no output for /Users/nikos/WebstormProjects/solar-popup/node_modules/vanilla-typescript/index.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/Users/nikos/WebstormProjects/solar-popup/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/nikos/WebstormProjects/solar-popup/node_modules/ts-loader/dist/index.js:21:12)
 @ ./src/SolarPopup.ts 2:0-46 73:34-42
 @ ./src/index.ts
