### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by cavalos0086** [s-panferov/awesome-typescript-loader#572]
I get the following error when I run the project in`webpack --watch` mode.  This is the stack trace:
```
 at Object.fs.readSync (fs.js:693:18)
    at tryReadSync (fs.js:557:20)
    at Object.fs.readFileSync (fs.js:600:19)
    at /Users/cavalos/Repos/ad-kargonaut/node_modules/awesome-typescript-loader/src/instance.ts:408:64
    at Array.map (<anonymous>)
    at Compiler.<anonymous> (/Users/cavalos/Repos/ad-kargonaut/node_modules/awesome-typescript-loader/src/instance.ts:405:14)
    at next (/Users/cavalos/Repos/ad-kargonaut/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.compiler.plugin (/Users/cavalos/Repos/ad-kargonaut/node_modules/webpack/lib/CachePlugin.js:48:5)
    at Compiler.applyPluginsAsyncSeries (/Users/cavalos/Repos/ad-kargonaut/node_modules/tapable/lib/Tapable.js:206:13)
    at Watching._go (/Users/cavalos/Repos/ad-kargonaut/node_modules/webpack/lib/Compiler.js:48:17)
    at Watching.invalidate (/Users/cavalos/Repos/ad-kargonaut/node_modules/webpack/lib/Compiler.js:142:9)
    at watcher.compiler.watchFileSystem.watch (/Users/cavalos/Repos/ad-kargonaut/node_modules/webpack/lib/Compiler.js:123:9)
    at Watchpack.watcher.once (/Users/cavalos/Repos/ad-kargonaut/node_modules/webpack/lib/node/NodeWatchFileSystem.js:45:4)
    at Object.onceWrapper (events.js:254:19)
    at Watchpack.emit (events.js:159:13)
    at Watchpack._onTimeout (/Users/cavalos/Repos/ad-kargonaut/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

```

After replacing `awesome-typescript-loader` with `ts-loader` the issue goes away. Any ideas?

Thanks.

**Comment by omril1** [comment]
Happens to me randomly about once a day when I'm developing.
Reproduced on windows 10.

I just restart webpack.
Not the worst thing, but still a bug.

**Comment by mikila85** [comment]
did anyone ever solve it?
from some when i do changes in a particular file half the times it compiles good and the other half just crashes like the above (could it be due to it being a large file and webstorm locking it for changes/saving while webpack/awesome-typescript-loader trying to read?
