### ISSUE TITLE
Issue with resolving paths

### ISSUE THREAD

**Issue by darewreck54** [s-panferov/awesome-typescript-loader#601]
Hi,

I'm currently noticing issue with when I define paths in the tsconfig.json file.  It throws the following the error below. 

Any advice on how to get past this error?

Thanks,
Derek

Looks like there are reference in other issue, but not sure if it's related since downgrading the typescript doesn't resolve the issue

Current Version:

```
  "webpack": "^4.16.2",
   "awesome-typescript-loader": "^5.2.0",
  "typescript": "^2.9.2",
```
   
tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "moduleResolution": "node",
    "declaration": false,
    "jsx": "react",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "baseUrl": ".",
    "lib": [
      "es2017",
      "dom"
    ],
    "paths" : {
      "common/*": ["common/src/*"]
    },
  },

  "compileOnSave": false,
  "exclude": [
    "node_modules"
  ]
}
```

web pack.config.dev.js

```
let path = require('path');
let HtmlWebpackPlugin = require('html-webpack-plugin');
let MiniCssExtractPlugin = require('mini-css-extract-plugin');
let webpack = require('webpack');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const ManifestPlugin = require('webpack-manifest-plugin');
const fs = require('fs');
let basePath = __dirname;
var TsConfigPathsPlugin = require('awesome-typescript-loader').TsConfigPathsPlugin;

module.exports = {
  resolve: {
    extensions: ['.js', '.ts', '.tsx']
  },
  resolve: {
    modules: [
      path.join(__dirname, 'common/src'),
      'common'
    ],
  },
  entry: {
    entity1: './entity1/src/main.tsx',
    entity2: './entity2/src/main.tsx'
  },
  optimization: {
    minimize: false, // debugging purpose
    runtimeChunk: 'single',
    splitChunks: {
      cacheGroups: {
        commons: {
          chunks: 'initial',
          minSize: 0,
          minChunks: 2
        },
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all'
        }
      }
    }
  },
  output: {
    path: path.join(basePath, 'dist'),
    filename: '[name]_bundle.js',
  },
  devtool: 'source-map',
  module: {
    rules: [{
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        loader: 'awesome-typescript-loader',
        options: {
          useBabel: true,
        },
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, "css-loader"]
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: 'assets/img/[name].[ext]?[hash]'
        }
      },
    ],
  },
  plugins: [
    new TsConfigPathsPlugin({
      configFile: './tsconfig.json',
    })
  ],
};

```
/sample/react-by-sample/01 HelloReact/node_modules/enhanced-resolve/lib/ModulesInRootPlugin.js:15
                const target = resolver.ensureHook(this.target);
                          ^
TypeError: resolver.ensureHook is not a function
    at ModulesInRootPlugin.apply (/sample/react-by-sample/01 HelloReact/node_modules/enhanced-resolve/lib/ModulesInRootPlugin.js:15:27)
    at PathPlugin.apply (/sample/react-by-sample/01 HelloReact/node_modules/awesome-typescript-loader/src/paths-plugin.ts:114:71)
    at webpack (/sample/react-by-sample/01 HelloReact/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/sample/react-by-sample/01 HelloReact/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/sample/react-by-sample/01 HelloReact/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/sample/react-by-sample/01 HelloReact/node_modules/yargs/yargs.js:563:18)
    at /sample/react-by-sample/01 HelloReact/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/sample/react-by-sample/01 HelloReact/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/sample/react-by-sample/01 HelloReact/node_modules/webpack/bin/webpack.js:165:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample@1.0.0 build: `webpack  --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-07-28T03_25_17_256Z-debug.log
```

**Comment by johnste** [comment]
I'm curious what you had configured wrong. I'm getting the same error (`resolver.ensureHook is not a function`) with the following plugin instantiation:
```js
new TsConfigPathsPlugin({ configFileName: "./tsconfig.json" })
```

**Comment by guy-shahine** [comment]
I faced the same issue. This post doesn't make it clear what the solution was: The placement of the plugin definition should be under the `resolve => plugins` property and not the high level `plugins` so it looks like this
`resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json'],
    plugins: [new TsConfigPathsPlugin()]
  },`
