### ISSUE TITLE
Does not work with jsx-typescript

### ISSUE THREAD

**Issue by gulbanana** [s-panferov/awesome-typescript-loader#7]
Hi, following the instructions in the README I installed jsx-typescript and set
loader: 'awesome-typescript-loader?compiler=jsx-typescript'

But webpack then produces the following stack trace:

```
ERROR in ./index.ts
Module build failed: TypeError: Cannot call method 'hasOwnProperty' of undefined
    at visit (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\dist\host.js:187:42)
    at visitNode (c:\Users\banana\Documents\code\cc\node_modules\jsx-typescript\bin\typescriptServices.js:3986:20)
    at Object.forEachChild (c:\Users\banana\Documents\code\cc\node_modules\jsx-typescript\bin\typescriptServices.js:4145:95)
    at visit (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\dist\host.js:199:22)
    at visitEachNode (c:\Users\banana\Documents\code\cc\node_modules\jsx-typescript\bin\typescriptServices.js:3997:30)
    at Object.forEachChild (c:\Users\banana\Documents\code\cc\node_modules\jsx-typescript\bin\typescriptServices.js:4094:24)
    at visit (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\dist\host.js:199:22)
    at State.findImportDeclarations (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\dist\host.js:201:9)
    at State.checkDependenciesInternal (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\dist\host.js:155:33)
    at c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\dist\host.js:147:46
    at tryCatcher (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\async.js:175:16)
    at Async._drainQueues (c:\Users\banana\Documents\code\cc\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\async.js:185:10)
```

**Comment by s-panferov** [comment]
It looks like that jsx-typescript is not aligned with the latest TS right now. We need to wait for its author to update the compiler.

**Comment by s-panferov** [comment]
jsx-typescript is out of sync with TypeScript 1.5, and it will not be updated in the future, I think. But there is a [PR](https://github.com/Microsoft/TypeScript/pull/2673) from the author of jsx-typescript that aims to add JSX support to TypeScript. So it's better to wait the official support.

I'll close the issue because I can't do anything with it right now.
