### ISSUE TITLE
'ERROR in Unexpected strict mode reserved word' on 0.15.0-rc.1

### ISSUE THREAD

**Issue by TomaszScisloGS** [s-panferov/awesome-typescript-loader#76]
Hi,

I've got ERROR in Unexpected strict mode reserved word in verion 0.15.0-rc1

node: 0.10.36
OS: Windows 7 64bit

Is it something on my site?

Regards,
Tomasz Ścisło

**Comment by s-panferov** [comment]
@TomaszScisloGS v0.15.0 is unstable right now and works only at node v5.0.0. I'll fix this asap.

**Comment by s-panferov** [comment]
@TomaszScisloGS I've just published v0.15.0-rc.2, could you please try it? It might work on your node version.

**Comment by TomaszScisloGS** [comment]
How about version 1.14.2?

**Comment by tscislo** [comment]
Unfortunately 0.15.0-rc.2 doesn't work with node 0.10.40. Any suggestions?

**Comment by s-panferov** [comment]
@tscislo v0.15.0 version finally works. Can you check?

**Comment by s-panferov** [comment]
@TomaszScisloGS please check v0.15.0

**Comment by TomaszScisloGS** [comment]
With 0.15.0 and node 0.10.36 I get:

Unhandled rejection TypeError: Cannot call method 'getOptionsDiagnostics' of undefined
    at Object.getPreEmitDiagnostics (h:\Projects\WDP\src\web\node_modules\typescript\lib\typescript.js:35386:35)
    at Compiler.<anonymous> (h:\Projects\WDP\src\web\node_modules\awesome-typescript-loader\dist.babel\instance.js:261:40)
    at Compiler.next (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:14)
    at Compiler.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:576:13)
    at Compilation.applyPluginsAsync (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:571:10)
    at Compilation.applyPluginsAsync (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:566:9)
    at Compilation.applyPluginsAsync (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:562:8)
    at Compilation.applyPluginsAsync (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Compilation.seal (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:524:7)
    at Compiler.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compiler.js:397:15)
    at h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\node_modules\tapable\lib\Tapable.js:103:11
    at Compilation.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:444:10)
    at Compilation.errorAndCallback (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:343:3)
    at Compilation.<anonymous> (h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:399:12)
    at h:\Projects\WDP\src\web\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:123:4
    at Array.forEach (native)

**Comment by tscislo** [comment]
Doesn't work for me either.

**Comment by s-panferov** [comment]
I've finally found the error source. Please try version v0.15.1

**Comment by tscislo** [comment]
Unfortunately now I'm facing this issue: https://github.com/s-panferov/awesome-typescript-loader/issues/77 and I cannot verify this one.

**Comment by s-panferov** [comment]
Issue was resolved by #79, landed as v0.15.2. Please try it.

**Comment by s-panferov** [comment]
@tscislo 	also please note, that default `tsconfig` which the generator generates [is not good](https://github.com/Swiip/generator-gulp-angular/pull/925).

**Comment by tscislo** [comment]
With 0.15.2 it works as expected. Thanks @s-panferov ! Can be closed now
