### ISSUE TITLE
Since 0.15.8 my webpack 'entry' is not being honoured.

### ISSUE THREAD

**Issue by mcrawshaw** [s-panferov/awesome-typescript-loader#87]
I have multiple webpack configurations with different entry points for my test suites.  Since the 0.15.8, all files from my tsconfig are being compiled, rather than just the dependency chain from my entry point.

The code change seems to have updated 'options.externals' to 'instance.options.externals'... not sure why this would impact...

@s-panferov any ideas?

Mark.

**Comment by gal-indegy** [comment]
+1
Before 0.15.8 *-tests.ts files were ignored (as should be), now for some reason they are being read.

Unhandled rejection Error: Cannot resolve module 'angular' in c:\git\graphology\src\typings\angularjs
    Required in c:\git\graphology\src\typings\angularjs\angular-amd-tests.ts
    at ResolutionError.Error (native)
    at new ResolutionError (c:\git\graphology\node_modules\awesome-typescript-loader\dist.babel\deps.js:487:88)
    at c:\git\graphology\node_modules\awesome-typescript-loader\dist.babel\deps.js:306:37
    at tryCatcher (c:\git\graphology\node_modules\bluebird\js\main\util.js:26:23)
    at CatchFilter.doFilter (c:\git\graphology\node_modules\bluebird\js\main\catch_filter.js:52:40)
    at CatchFilter.tryCatcher (c:\git\graphology\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\git\graphology\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (c:\git\graphology\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (c:\git\graphology\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (c:\git\graphology\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\git\graphology\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\git\graphology\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by s-panferov** [comment]
Fixed in v0.15.10

**Comment by mcrawshaw** [comment]
Thanks, I can also confirm it's working now.
