### ISSUE TITLE
Cannot read property 'NodeJs' of undefined in 0.15.9

### ISSUE THREAD

**Issue by Luchillo** [s-panferov/awesome-typescript-loader#88]
In ionic 2 uses awesome-typescript-loader v 0.12.0-rc.2, updating to 0.15.9 breaks it with the error stack:
>Unhandled rejection TypeError: Cannot read property 'NodeJs' of undefined
    at buildEnumMap (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/tsconfig-utils.js:48:48)
    at Object.rawToTsCompilerOptions (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/tsconfig-utils.js:63:29)
    at Object.ensureInstance (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/instance.js:127:32)
    at _callee2$ (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/index.js:64:47)
    at tryCatch (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/index.js:30:41)
    at /Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/index.js:33:9
    at tryCatcher (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/bluebird/js/main/promise.js:70:37)
    at __awaiter (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/index.js:8:12)
    at compiler (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/index.js:51:12)
    at Object.loader (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2/node_modules/awesome-typescript-loader/dist.babel/index.js:47:14)
    at WEBPACK_CORE_LOADER_EXECUTION (/usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)

>./www/app/app.js
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
    at nextLoader (/usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:159:13)
    at nextLoader (/usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /usr/local/lib/node_modules/ionic/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/usr/local/lib/node_modules/ionic/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /usr/local/lib/node_modules/ionic/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ multi main (CLI v2.0.0-beta.9)

**Comment by tlancina** [comment]
This happens if you haven't updated your Typescript version as well. `NodeJs` path style resolution was introduced in 1.7 I believe.

**Comment by s-panferov** [comment]
It seems that you have this in your tsconfig.json:

```
"moduleResolution": "NodeJS",
```

Please replace it with 

```
"moduleResolution": "node",
```

**Comment by Luchillo** [comment]
Actually that was quite some time ago, updating to 0.15.9 and removing that `moduleResolution` variable, along with installing typescript ^1.7.5 fix this issue.
