### ISSUE TITLE
Unit Tests do not work since v0.15.8

### ISSUE THREAD

**Issue by 4kochi** [s-panferov/awesome-typescript-loader#90]
Since this change my unit tests does not work any more. 0.15.7 -> v0.15.8 (1715bee8be0c2397ad3564e96ecb2fd05b77d81d)

My error:

```
ERROR in ./src/app/components/main/main.controller.spec.ts
Module build failed: Error: File /Users/andreaskrummsdorf/web/mms2-web/src/app/components/main/main.controller.spec.ts was not found in program
    at State.emit (/Users/andreaskrummsdorf/web/mms2-web/node_modules/awesome-typescript-loader/dist.babel/host.js:254:27)
    at transform (/Users/andreaskrummsdorf/web/mms2-web/node_modules/awesome-typescript-loader/dist.babel/index.js:168:48)
    at _callee2$ (/Users/andreaskrummsdorf/web/mms2-web/node_modules/awesome-typescript-loader/dist.babel/index.js:218:42)
    at tryCatch (/Users/andreaskrummsdorf/web/mms2-web/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/andreaskrummsdorf/web/mms2-web/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/andreaskrummsdorf/web/mms2-web/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (/Users/andreaskrummsdorf/web/mms2-web/node_modules/awesome-typescript-loader/dist.babel/index.js:30:41)
    at onfulfill (/Users/andreaskrummsdorf/web/mms2-web/node_modules/awesome-typescript-loader/dist.babel/index.js:17:17)
    at tryCatcher (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andreaskrummsdorf/web/mms2-web/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 @ multi main
```

Here is my gulp config:

```
var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');

var browserSync = require('browser-sync');
var webpack = require('webpack-stream');

var $ = require('gulp-load-plugins')();

function webpackWrapper(watch, test, callback) {
    var webpackOptions = {
        resolve: { extensions: ['', '.ts'] },
        watch: watch,
        module: {
            preLoaders: [{ test: /\.ts$/, exclude: /node_modules/, loader: 'tslint-loader' }],
            loaders: [{ test: /\.ts$/, exclude: /node_modules/, loaders: ['ng-annotate', 'awesome-typescript-loader'] }]
        },
        output: { filename: 'index.module.js' }
    };

    if (watch) {
        webpackOptions.devtool = 'inline-source-map';
    }

    function webpackChangeHandler (err, stats) {
        if (err) {
            conf.errorHandler('Webpack')(err);
        }
        $.util.log(stats.toString({
            colors: $.util.colors.supportsColor,
            chunks: false,
            hash: false,
            version: false
        }));
        browserSync.reload();
        if (watch) {
            watch = false;
            callback();
        }
    }

    var sources = [path.join(conf.paths.src, '/app/index.module.ts')];
    if (test) {
        sources.push(path.join(conf.paths.src, '/app/**/*.spec.ts'));
    }

    return gulp.src(sources)
        .pipe(webpack(webpackOptions, null, webpackChangeHandler))
        .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app')));
}

gulp.task('scripts', function () {
    return webpackWrapper(false, true);
});
```

**Comment by s-panferov** [comment]
@4kochi version v0.15.10 must fix this. Please check.

**Comment by 4kochi** [comment]
Works fine now with `v0.15.10`. Thanks.
